### ISSUE TITLE
Please update the Safari filters' translations in Traditional Chinese language file.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#686] opened 2018-03-06 10:48 UTC
I don't know if it's due to the old language file left on the device since it's the same situation both with AG Pro beta v2.0.0(140) and v2.0.0(143).
**After installing AG Pro beta v2.0.0(140)/(143), the interface of Safari filters is Simplified Chinese translations from the beginning.
After restarting AG Pro beta v2.0.0(140)/(143), the interface of Safari filters became to English.**
Is this a bug?

But the interface of Safari filters is still not Traditional Chinese translations.
https://github.com/AdguardTeam/AdguardForiOS/issues/673#issuecomment-369172364
@aalpatkina 
@ameshkov 
You told me to not worry.
That's why I always worry and often remind you..........
May I see Traditional Chinese translations for Safari filters in v2.0.1?

Thanks...

**Comment by lancelot-moon** [comment] 2018-03-07 21:23
@ameshkov 
@IvanIin 

I just tried beta v2.0.0(146).
Even the situation becomes the worst.

In beta AG Pro v2.0.0(140):
After installing AG Pro v2.0.0(143), the interface of Safari filters is Simplified Chinese translations from the beginning.
After clicking "Check for updates" and restarting AG Pro v2.0.0, the interface of Safari filters became to English.
Is this a bug?

In beta AG Pro v2.0.0(146):
The interface of Safari filters is always Simplified Chinese translations.

@aalpatkina 
>And about translations for filters: I know that you've completed translations and checked all updated phrases in "Miscellaneous" project. Thank you for that. We'll update filters translations very soon. Please do not worry :)

How can I not worry?
Simplified Chinese translations are still wrongly used for Safari filters in Traditional Chinese language file of beta v2.0.0(146).

Ivanlin, locales 'zh-CN' or 'zh' is Simplified Chinese.
'zh-TW' is Traditional Chinese for Taiwan.
But you constantly wrongly use 'zh-CN' or 'zh' for Traditional Chinese.

Please, it should be not difficult to solve the issue as long as you correctly use 'zh-TW' for Safari filters in Traditional Chinese language file.

May you give the link for letting me check the content of 'zh-TW' in Safari filters?

Such like the link of AdGuard Assistant.
https://github.com/AdguardTeam/AdguardAssistant/commit/aad8861a8edd721768272aa95f9d4f265f4fd818

I want to check if they're Traditional Chinese translations in locale 'zh-TW'.

**Comment by ameshkov** [comment] 2018-03-07 21:27
Here it is:
https://filters.adtidy.org/ios/filters_i18n.json

It is okay on the server side. @IvanIin please be careful with that.

**Comment by lancelot-moon** [comment] 2018-03-07 21:35
This is the video about Safari filters in beta v2.0.2(146).
https://youtu.be/NpLAfb8slzE

Simplified Chinese translations are still wrongly used for Safari filters in Traditional Chinese language file.
I'll check again in the next beta version.

Sorry to bother you.
Please go to sleep early.
Good night, AdGuard team.

**Comment by lancelot-moon** [comment] 2018-03-09 16:53
@IvanIin 

You never solve the translation issue for Safari filters.

However, you let v2.0.2(146) released on App Store.................................................................
So will you soon do updates again???

**Comment by ameshkov** [comment] 2018-03-10 01:35
We will soon resolve it, don't worry :)

The hotfix was required to solve the issue with the disappearing subscriptions.

**Comment by lancelot-moon** [comment] 2018-03-11 03:59
Forgive for my unclear meaning.
I meant that early applying Traditional Chinese translations for filters in that hotfix was wasted, which is a pity.
Eh, I found AdGuard team recently did some updates for filters' strings on oneskyapp.
Maybe that's why it's delayed.

Because Simplified Chinese translations in Traditional Chinese language file tormented AdGuard's Taiwanese users for many years, I am specially concerned with the issue.

Sorry to bother AdGuard team.

**Comment by ameshkov** [comment] 2018-03-11 10:30
> I meant that the chance of early applying Traditional Chinese translations for filters in that hotfix was wasted, which is a pity.

The main issue here is not oneskyapp, but the fact that AG for iOS fails to use the proper language.

It **should** use the following logic:

1. Look for the translation with the full language code (`pt_BR` or `zh_TW` for instance)
2. If not found, strip the country code and look for the translation with a short language code (`pt` or `zh`)
3. If nothing found, use `en`

The problem is that it fails to find the proper translation on step 1, and it should be fixed on the app side.

**Comment by lancelot-moon** [comment] 2018-03-16 17:28
How about the following logic: **Don't consider zh.**

1. Look for the translation with the full language code (pt_BR or zh_TW for instance)
2. If not found, strip the country code and look for the translation with a short language code (pt or **en**)
3. If nothing found, use en

**Closed** 2018-03-19 14:42 UTC
Labels: Bug, Localization

**Comment by lancelot-moon** [comment] 2018-03-19 15:55
Have you solve the issue of Traditional Chinese translations for filters in the next beta version?
If not, please reopen the issue.
Otherwise, @IvanIin will always ignore the issue, such like v2.0.0 and v2.0.2.
Originally, this should be solved in v2.0.0 and v2.0.2, but it was just a bounced cheque...

**Comment by ameshkov** [comment] 2018-03-19 17:02
@lancelot-moon could you please check it in the regular AdGuard for iOS (not Pro)?

The issue should've been fixed there (so the fix will arrive in the next Pro update as well)

**Comment by lancelot-moon** [comment] 2018-03-19 17:51
I went to install free AdGuard for iOS v2.0.2(92).
Yes, you have solved it!!!
Thank AdGuard team very much!!!

They're Traditional Chinese interface. :D
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/Lk31ZHd.png)

![image](https://i.imgur.com/UKS3GMI.png)
</details><br/>
