### ISSUE TITLE
Activity Log Isn't Reliable

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1798] opened 2021-07-26 14:49 UTC
### Issue Details

- **AdGuard version:**
  - AG Pro Beta iOS 4.2.0 (704)
- **Device model and storage size:**
  -  iPhone 11 Pro Max and iPad 11 Pro. 
- **Operating system and version:**
  -  iOS 14.6
- **Browser or App:**
  -  AG Pro Beta 4.2.0

### Expected Behavior

 AG log should reflect what is really happening.   

### Actual Behavior

 For instance it says that the request 
[http://www.wlfi.com](http://www.wlfi.com) is blocked because matching a rule from https://assets.windscribe.com/extension/ws/malwaredomains.txt. 

However the domain wlfi.com isn't present in the filter rules.

### Screen Shot

![image](https://user-images.githubusercontent.com/49731083/125326154-0370c180-e342-11eb-82b0-07906bb0a913.png)

**Comment by zzebrum** [comment] 2021-07-27 12:07
most probably it's a duplicate of #1732

**Closed by zzebrum** 2021-07-27 12:07 UTC

**Comment by Quorum75** [comment] 2021-07-27 21:07
Yes it, but I close the other one as it was not related to DNS
