### ISSUE TITLE
Bug: Reinstall required to get latest lists

### ISSUE THREAD

**Issue by fvdm** [AdguardTeam/AdguardForiOS#1146] opened 2019-07-25 12:23 UTC
To update the available filter lists you have to reinstall the app. Updating from the App Store or using the updater within the app doesn’t make new lists available.

For example, after I completely reinstalled the app I got a new list ‘Web Annoyances Ultralist’ available in Filters > Annoyances, that wasn’t there before. Also the UI has gained tags and country flags that didn’t come with the App Store update.

Both app installs (before and after reinstall) were version 3.0.1(156) and the internal updater was ran multiple times and up to date.

### Steps to reproduce

1. Have AdGuard installed before new lists are added to the app.
2. Update the app from the App Store
3. Open AdGuard: the new lists are **not** added to the app.
4. Delete the app and reinstall from App Store
5. Now all lists are available.

### Expected behavior

When the app is updated from the App Store the available lists should be updated immediately.

### Actual behavior

App Store updates don’t update the available lists. Only after full app deletion and reinstall you can get the current lists in the app.

<details><summary>Screenshot:</summary>

![FDCF23DE-EBB5-43DA-90E9-DB0F133FDED5](https://user-images.githubusercontent.com/93784/61873694-daea2580-aee6-11e9-97b6-9bf58f2d44ac.jpeg)

</details>

### Customer ID 

_reporting feature doesn't exist_

### Your environment

* Device model and storage size: iPhone 8 64GB
* Operating system and version: 12.3.1
* Browser: Safari
* Wi-fi and mobile internet connection

**Comment by zznosar** [comment] 2019-07-28 12:24
I second this. adGuard Pro just needs to be pulled down to get the latest list. The non Pro requires reinstallation. @ameshkov can you please tag this as a bug and assign to a release?

**Comment by lancelot-moon** [comment] 2019-07-29 10:39
It's a duplication.
Already have a feature request.
https://github.com/AdguardTeam/AdguardForiOS/issues/958

**Comment by zznosar** [comment] 2019-07-29 11:42
I think this is different in what you raise. This is a bug not a feature request. Your ticket is about translation. This is about missing filter list. AG Pro does not have this issue. Only v3 of normal AdGuard.

**Comment by lancelot-moon** [comment] 2019-07-29 12:10
`Sync filters' translations and lists by checking for filters' updates.`

In the past, I already found the issue.
You actually didn't read my content.
It should sync not only filters list but also those filters' descriptions/translations.
Simply, AG v3 doesn't have the feature to sync filters' list and descriptions/translations.

**Comment by zznosar** [comment] 2019-07-29 12:28
I read it and understood it clearly that your main request is about translation. You should have separated the two - one ticket for the list and one for translation. I suggest to leave this ticket open as the details here are very specific and easily understandable. Your details in your  request are generic and focuses in translation. It does not even detail what the issue is. One look in your request all i can see is translation request about the filter list.

**Comment by lancelot-moon** [comment] 2019-07-29 12:49
https://github.com/AdguardTeam/AdguardForiOS/issues/958#issuecomment-510090513

> AG v3.0.1 (156) uses outmoded filters list and description.

19 days ago, I notified AG team that AG v3.0.1 (156) uses **outmoded filters list** and description.
I focus on **filters list** and their descriptions/translations.
My main request is NOT only about translations.
You should not contort the fact.
While synchronizing filters list, those filters' descriptions/translations should be updated at the same time.

**Comment by zznosar** [comment] 2019-07-29 13:16
If that is what you meant in your ticket, then update your details and be more specific. I’m not twisting the details and i’m not saying you are wrong. I’m just saying based on what i read between this and your ticket. Your ticket clearly lacks details. Even the comment you put still does not state the details. If i’m the developer, i would have not easily understood your requirement and will ask you to provide more details and to separate the translations issue and the filter list issue.

I will let the team decide to have this open or not, but i strongly believe that this should be track separately. Pull to refresh is an existing feature in v2 which v3 lacks. This should not be a feature request. A feature request is something not existing before. 

The discussion is getting out of topic. Team, please just fix this and remove these comments if required. 

Thank you.

**Comment by lancelot-moon** [comment] 2019-07-29 13:37
Synchronizing app's filters data (including filters list, name and description/translation) with AG server is **ONE thing**.

> Is there a convenient way to sync filters information with AG server by users ourselves?

I don't think you don't understand what "synchronize" means.

You can't contort that this isn't a duplication with mine.
Anyway, leave this report or not, which is decided by AG team.

**Comment by zznosar** [comment] 2019-07-29 14:05
If that is what you think then ok. Let AdGuard decide. I will remove my other reply as this is really going out of topic. Just retain the first one,

Apologies @fvdm for hijacking your issue, but I support you in this.

**Comment by ameshkov** [comment] 2019-08-02 13:41
Dup of https://github.com/AdguardTeam/AdguardForiOS/issues/1146 indeed

**Closed by ameshkov** 2019-08-02 13:41 UTC
Labels: Duplicate
