### ISSUE TITLE
Adguard not compatible with iOS 11

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardForiOS#407] opened 2017-06-05 22:01 UTC
I know it‘s a beta and very early, but I really hope you guys can fix this relativley quick anyway ;)

edit: If it‘s not an iOS issue though

**Comment by ameshkov** [comment] 2017-06-05 22:06
That was fast:)

**Comment by ameshkov** [comment] 2017-06-05 22:07
Any details on the issue?

**Comment by danidoedel** [comment] 2017-06-05 22:23
Yeah couldn‘t await it ;)

Can‘t activate any filter. 
Looks like the filters can‘t be loaded into safari:

![img_5935](https://cloud.githubusercontent.com/assets/10995998/26805840/3ce57262-4a4e-11e7-916c-60a274008628.PNG)

**Comment by ameshkov** [comment] 2017-06-05 22:24
At least there're no issues with the VPN:) We'll check it, thank you for reporting it!

**Comment by danidoedel** [comment] 2017-06-05 22:31
Yeah VPN seems to work this time :)

No problem! I really hope there are just a few little changes required.

**Comment by danidoedel** [comment] 2017-06-05 22:41
Maybe that‘s somehow related, but I thought I would post it anyway:

![img_5936](https://cloud.githubusercontent.com/assets/10995998/26806361/ba0647f6-4a50-11e7-8471-5151af6334cd.PNG)

**Comment by ameshkov** [comment] 2017-06-05 22:44
Nah, that's different (worth filing a bug report anyways:))

**Comment by ameshkov** [comment] 2017-06-05 22:45
On the other hand, judging by the error message, it seems that we're aware of this particular issue already

**Comment by danidoedel** [comment] 2017-06-05 22:49
Yeah that‘s something I thought too... 

I leave it up to you if you want to file another bug report about that :)

**Comment by danidoedel** [comment] 2017-06-05 22:52
But wait that doesn‘t happen on every website. Others are working fine. Did the assistant work on github on iOS 10?

**Comment by ameshkov** [comment] 2017-06-05 22:53
Depends on the website's content security policy

**Comment by danidoedel** [comment] 2017-06-05 22:58
Ok, then it‘s not an issue. How did I never notice that? :D Bad luck Github was the first page I checked...
Sorry for the confusion. Then there is „just“ the first issue.

**Comment by danidoedel** [comment] 2017-06-05 23:27
Ok I was able to narrow the issue down a bit. 

Regarding the Adguard filters, every filter works except the English, French and simplyfied domain name filter.

**Comment by maciboy** [comment] 2017-06-06 19:27
I‘m experiencing the same issue with the „normal“ Adguard version 
Filters can not be loaded into Safari. 
For me it seems as if disabling only the english filter helps, leaving the rest untouched/active

**Comment by gingerbeardman** [comment] 2017-06-07 19:31
Is it possible the limit of the number of rules has been changed?

**Comment by ameshkov** [comment] 2017-06-08 15:54
Just installed iOS beta, we'll soon learn what's wrong with this.

**Comment by gingerbeardman** [comment] 2017-06-08 16:43
Seems to be happening with other content blocker on my device. 

I reported the issue to Apple as bug 32623684

**Comment by BrokenHope** [comment] 2017-06-08 19:37
The release notes for ios 11 Beta 1 state the following.

'The amount of memory used to load Safari Content Blocker rules has temporarily
increased. This may cause your extension to exceed its memory limits. (32330531)'

I'm going to assume that's what is causing the problem and hopefully it will be resolved by Apple in a futre beta version.

**Comment by ameshkov** [comment] 2017-06-11 14:03
> 'The amount of memory used to load Safari Content Blocker rules has temporarily
> increased. This may cause your extension to exceed its memory limits. (32330531)'

Yeah, that's exactly how it looks like on our side. Large filters just cannot be registered, while it's able to compile smaller filters.

**Comment by jo2dan23** [comment] 2017-06-14 16:10
So is this a problem that needs to be fixed on adguard side or ios?

**Comment by jo2dan23** [comment] 2017-06-14 19:55
I know ios11 is in beta but adguard was making it really really slow. I had to disable the vpn. Anyone else?

**Comment by gingerbeardman** [comment] 2017-06-14 19:57
the beta is super slow due to all the debug logging they have enabled. it's a beta :)

**Comment by ameshkov** [comment] 2017-06-15 11:47
> I know ios11 is in beta but adguard was making it really really slow. I had to disable the vpn. Anyone else?

The latest one? We're adding more and more logging to figure what's wrong with #404 

> So is this a problem that needs to be fixed on adguard side or ios?

Should be fixed on the iOS side.

**Comment by echodreamz** [comment] 2017-06-21 21:41
Still no go on iOS 11 Beta 2 for those wondering :)

**Comment by planetf1** [comment] 2017-06-22 16:52
Just came here after trying beta 2. I had english, spyware,annoyances, unblocking useful, mobile ads, safari. easylist enabled with iOS 10.3.3b3. Any recommendations as to a good cut down set that sits under the iOS11 memory limit? I'll experiment anyway!"

**Comment by BrokenHope** [comment] 2017-06-22 16:56
I'm using Mobile Ads, Safari and EasyList, haven't really noticed anything getting through.

**Comment by ameshkov** [comment] 2017-06-22 16:57
EasyList fits??

**Comment by BrokenHope** [comment] 2017-06-22 16:58
Yeah I was surprised that I could use EasyList but not the english filter..

**Comment by ameshkov** [comment] 2017-06-22 16:58
I guess it means we're on the very edge.

Adguard's English filter is 10-15% bigger than the EasyList.

**Comment by BrokenHope** [comment] 2017-06-22 17:00
I don't suppose it's possible to easily cut it down temporally some how until Apple fix the bug? Perhaps make a new filter list just for iOS 11 beta. I'd prefer to be using the tailored English filter over the generic EasyList filter.

**Comment by ameshkov** [comment] 2017-06-22 17:06
That's possible, won't help everybody though. There are a lot of people who rely on language-specific filters, which aren't small.

JFYI, here are the iOS versions of these filters:

English filter: http://filters.adtidy.org/ios/filters/2_optimized.txt
EasyList: http://filters.adtidy.org/ios/filters/101_optimized.txt

**Comment by gingerbeardman** [comment] 2017-06-22 17:54
Thanks @brokenhope I'm using that combo for now

**Comment by planetf1** [comment] 2017-06-23 07:28
Assuming english, How does the optimized list above (english, easylist) compare to the set I mentioned (annoyances, useful ads, mobile ads, safari filter) very approximately?
Also if more appropriate, how do I import a user filter into Adguard on iOS?

**Comment by ameshkov** [comment] 2017-06-23 09:52
> How does the optimized list above (english, easylist) compare to the set I mentioned (annoyances, useful ads, mobile ads, safari filter) very approximately?

All the other filters are based on the English + EasyList. The only exception is mobile ads, it can duplicate some of the existing rules but make them a bit more "strict". However, it does not replace the English filter anyway.

> Also if more appropriate, how do I import a user filter into Adguard on iOS?

There's no explicit "import" procedure. You can simply copy/paste rules as a text, though.

**Comment by AtomicCoding** [comment] 2017-06-27 19:28
(I'm having the same issue, but it only happens to me when I enable a large filter and then a smaller filter, the smaller one will give me an error)

**Comment by ThePixelDeveloper** [comment] 2017-07-05 07:42
Just thought I'd leave a comment here as well.

I'd like to add Easy List, Easy Privacy and Fanboys Annoyances and it seems there's an internal limit. I can enable any one first, but anything after it gets the error.

**Comment by ameshkov** [comment] 2017-07-10 16:29
> I'd like to add Easy List, Easy Privacy and Fanboys Annoyances and it seems there's an internal limit. I can enable any one first, but anything after it gets the error.

According to https://github.com/AdguardTeam/AdguardForiOS/issues/407#issuecomment-307205651 that indeed happens because of an internal memory limit, but that's not intended and should be fixed in the following updates.

**Comment by BrokenHope** [comment] 2017-07-10 17:29
Looks to be resolved in dev beta 3 despite the release notes still listing it as a known issue.

**Comment by ameshkov** [comment] 2017-07-10 17:50
@BrokenHope thanks for letting us know!
@vozersky could you please check it?

**Comment by danidoedel** [comment] 2017-07-10 18:26
Yep it seems you are able to activate the filters, but filtering doesn‘t really work:

![img_6278](https://user-images.githubusercontent.com/10995998/28033280-fdb06b3a-65ad-11e7-961b-b1754d10805a.PNG)

**Comment by maciboy** [comment] 2017-07-10 18:52
@danidoedel Release notes tell that this is a known issue and that one should de- & reactivate the blocker in Settings/Safari

**Comment by danidoedel** [comment] 2017-07-10 18:57
@maciboy Yes I know that as I read release notes. Doesn‘t help though........

**Comment by BrokenHope** [comment] 2017-07-10 18:58
Try doing a filter update in adguard that resolved the issue of it not blocking ads on my iPhone.

**Comment by danidoedel** [comment] 2017-07-10 19:03
Of course I did that... :D

**Comment by ThePixelDeveloper** [comment] 2017-07-11 07:53
Seems to be fixed the new iOS beta. Can load multiple new lists.

**Comment by vozersky** [comment] 2017-07-11 11:14
> Seems to be fixed the new iOS beta. Can load multiple new lists.

@zebrum please test with iOS 11 b3

**Comment by zebrum** [comment] 2017-07-11 12:30
confirmed, it is possible now to load english or other filters.

**Comment by gingerbeardman** [comment] 2017-07-11 14:36
Works for me

**Comment by ameshkov** [comment] 2017-07-13 08:40
Thanks to everybody! I guess it can be closed now.

**Closed by ameshkov** 2017-07-13 08:40 UTC
Labels: iOS Bug
