### ISSUE TITLE
[3.0 Beta] in Custom filters liet button for open source url don’t work

### ISSUE THREAD

**Issue by minsk21** [AdguardTeam/AdguardForiOS#1070] opened 2019-06-16 09:53 UTC
### Steps to reproduce

When you press a button, nothing happen

### Customer ID 

* Operating system and version: iOS 11.4.1

**Comment by ameshkov** [comment] 2019-07-03 11:06
Duplicate of https://github.com/AdguardTeam/AdguardForiOS/issues/1093

**Closed by ameshkov** 2019-07-03 11:06 UTC
Labels: Bug, P4: Low
