### ISSUE TITLE
`Report an issue` button in Web Extension is hidden and made as link

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForiOS#2128] opened 2023-02-06 01:11 UTC
### Issue Details

The `Report an issue` button in the Web Extension is hidden by default, making it hard to find if the user doesn't know it's supposed to be there. In the old Share extension you didn't hide it, why are you hiding it here?

And also, after expanding this button, for some reason it turns out to be made as a regular link in the text, and not as a button (like other buttons and as it was done in the Share extension), which makes it harder to click on it.

<details><summary>Screenshot</summary>

![IMG_3702](https://user-images.githubusercontent.com/19418601/216859484-9fb0234c-d7d8-40de-8e6e-8211bff3998c.PNG)

![IMG_3703](https://user-images.githubusercontent.com/19418601/216859491-0779bf0f-4cf2-4d1b-b4a5-07c06779f308.PNG)

</details>

### Proposed solution

Don't hide the `Report an issue` button by default, and also make it a real button.

**Comment by jslawler** [comment] 2023-02-06 05:11
#2015

**Comment by Versty** [comment] 2023-02-08 12:09
@rakleed Closed as a duplicate of #2015.

**Comment by rakleed** [comment] 2023-02-08 12:11
@Versty but why did you close the issue if the problem is not solved? And my issue only partially duplicates #2015, because I also propose to make a button instead of the Report an issue link.

**Closed** 2023-02-08 12:10 UTC
Labels: Resolution: Duplicate, Status: Closed, improvement

**Comment by Versty** [comment] 2023-02-08 12:43
@rakleed This feature request is closed because it is almost the same with `2015`, but your proposed solution differs. 
We discussed both options with the developers and designers, and decided to keep the `Report an issue` link in its original place for the near future.
