### ISSUE TITLE
iPadOS Widget Does Not Load

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1928] opened 2022-02-05 11:56 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  AG Pro Beta 4.3.2 (937)
- **Device model and storage size:**
  -  iPad Pro 11 Pro 256Go
- **Operating system and version:**
  -  iPadOS 15.3
- **Browser or App:**
  -  N/A

### Expected Behavior

 Loading of AG widget. 

### Actual Behavior

 AG Pro widget doesn't lo1d. 

### Screenshots

>  ![image](https://user-images.githubusercontent.com/49731083/152641012-efa21304-cdd6-489a-9527-dec042f55db5.jpeg)

<details><summary>Screenshot:</summary>

</details>

### Additional Information

 Widget works on iOS though.

**Comment by ameshkov** [comment] 2022-02-05 14:11
I am pretty sure this is actually the duplicate of #1849, the widget randomly does not load and we cannot find any reason for that:(

I think the only way to completely solve this issue is to conduct a pretty serious rework of the widget code which we're planning to do anyway.

**Closed by ameshkov** 2022-02-05 14:11 UTC

**Comment by Quorum75** [comment] 2022-02-08 16:06
> I am pretty sure this is actually the duplicate of #1849, the widget randomly does not load and we cannot find any reason for that:(
> 
> 
> 
> I think the only way to completely solve this issue is to conduct a pretty serious rework of the widget code which we're planning to do anyway.

I agree to disagree. 
In fact it works on iOS iPhone, at least on my side since AG 4.3, but not on iPadOS which is in fact different. That's why I created a different post.
