### ISSUE TITLE
Please change the description for "Auto Update over Wi-Fi only" according to the different purposes.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#689] opened 2018-03-06 18:21 UTC
@ameshkov 

If you let "Auto Update over Wi-Fi only" include not only Safari filters but also Privacy Settings' subscriptions........
https://github.com/AdguardTeam/AdguardForiOS/issues/682

**Besides this issue, you need to together do the change from another issue in the same next version**, https://github.com/AdguardTeam/AdguardForiOS/issues/663.

The original description for "Auto Update over Wi-Fi only" is a little ambiguous.
So I request to clearly define the description.

1. If the purpose of "Auto Update over Wi-Fi only" in your design is for those who want to save the data usage of cellular network.............

Please change the description for "Auto Update over Wi-Fi only".
Original: "If this setting is enabled, AdGuard will only use WiFi for background filter updates." <- It's "Wi-Fi", not "WiFi". Please fix it on oneskyapp.
New: "**If this setting is enabled, AdGuard will only use Wi-Fi for the auto updates of Safari filters & Privacy Settings' subscriptions in the background, and then automatically or manually updating them via cellular network is not allowed.**"
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/KEzTw9b.png)
</details><br/>

We maybe also need to notify users to disable the setting (a pop-up) if they forget enabling "Auto Update over Wi-Fi only" in the past and want to now manually update Safari filters or Privacy Settings' subscriptions via cellular network.

The pop-up of notification:
"**If you want to manually check for updates for Safari filters or Privacy Settings' subscriptions via cellular network, you need to disable "Auto Update over Wi-Fi only" in the Advanced Settings.**"
When clicking "Check for updates" for Safari filters via cellular network with "Auto Update over Wi-Fi only" enabled:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/yUszhfj.png)
</details><br/>

When clicking "Check for updates" for subscriptions via cellular network with "Auto Update over Wi-Fi only" enabled:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/54tPl8N.png)
</details><br/>

2. If the purpose of "Auto Update over Wi-Fi only" in your design is for on top of manually updating at any time, automatically updating in the background when using Wi-Fi.............

I guess that this should be your purpose in your design.
The above pop-up of notification is unnecessary.
We need to clearly define the description for "Auto Update over Wi-Fi only".
Original: "If this setting is enabled, AdGuard will only use WiFi for background filter updates." <- It's "Wi-Fi", not "WiFi". Please fix it on oneskyapp.
New: "**On top of manually updating Safari filters & Privacy Settings' subscriptions via cellular network / Wi-Fi, if this setting is enabled, AdGuard will only use Wi-Fi for their auto updates in the background.**"

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/w3nd0df.png)
</details><br/>

B/R

**Comment by camelot-sun** [comment] 2018-03-06 19:39
> manually updating them via cellular network is not allowed.

I don’t think many will be happy if we do this and update the description like you suggested.

As I understood correctly, if that is ON, you can only automatically update the filters via wifi. Manual Update via cellular is still possible.

Safe to say that not all people are dumb not to understand what this mean. Even non english people like me, at first read, I know what it means. 

Brief and concise is much prefer than having too many words as this will only raise questions and confusion.

Just my opinion though. Let see what the team will say.

**Comment by lancelot-moon** [comment] 2018-03-06 20:02
I also guess that AdGuard team use my 2nd point in their design.

But some apps are designed that they update via Wi-Fi only for saving the data usage of cellular network.
This is not rare.
That's why I think that the original description for "Auto Update over Wi-Fi only" is a little ambiguous.
It's necessary to clearly define the description renew.

**Comment by camelot-sun** [comment] 2018-03-06 20:19
You thoughts are valid. Let see what the team will decide.

By the way, its very early morning in Taiwan! You need rest! I saw your contributions and comments here in Github and you’ve been a wake for a while!

**Comment by ameshkov** [comment] 2018-03-10 00:52
> I also guess that AdGuard team use my 2nd point in their design.

Yep, that's how it works.

**Comment by Versty** [comment] 2024-07-04 10:00
@lancelot-moon Closed as a duplicate of https://github.com/AdguardTeam/AdguardForiOS/issues/690

**Closed** 2024-07-04 10:00 UTC
Labels: Enhancement, Localization, P4: Low, Resolution: Duplicate, Status: Resolved, Low, Priority: P3
