### ISSUE TITLE
iOS 18: DNS protection not working in Adguard IOS app

### ISSUE THREAD

**Issue by jansiee** [AdguardTeam/AdguardForiOS#2348] opened 2024-07-03 10:35 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.4

### Environment

- OS: 18.0
- Device: iPhone 15 Pro Max

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

VPN enabled on IOS when DNS protection on

### Actual Behavior

DNS protection goes off immediately after enabling

### Screenshots

<details><summary>Screenshot 1</summary>

</details>
![IMG_9477](https://github.com/AdguardTeam/AdguardForiOS/assets/119403098/eebb872e-351c-4c35-accf-87248aa71997)
![IMG_9476](https://github.com/AdguardTeam/AdguardForiOS/assets/119403098/dbb63e62-ea0c-417c-bc2b-4c62e69b78ec)

https://github.com/AdguardTeam/AdguardForiOS/assets/119403098/11a3517d-3974-4411-8801-067f28e7c1dd

### Additional Information

So i'm trying to use the DNS filter on iOS, because i don't use Safari as my browser, but i can't enable it. It doesn't install the VPN connection on my phone. Perhaps it has something to do with iOS 18 beta?

**Comment by Versty** [comment] 2024-07-22 11:20
@jansiee Seems like the issue is fixed on iOS 18 Developer Beta 3. Could you confirm on your side?

**Comment by Versty** [comment] 2024-07-31 08:48
@jansiee Any updates?

**Comment by jansiee** [comment] 2024-07-31 11:02
I'm sorry, was on holiday. 

Yes it is fixed! I saw that it was fixed already a few days after my ticket.

**Closed as completed** 2024-07-31 11:03 UTC
Labels: Bug, Resolution: Fixed, Status: Closed, Priority: P4
