### ISSUE TITLE
Filters for cdn.ampproject.org are not loaded

### ISSUE THREAD

**Issue by yous** [AdguardTeam/AdguardForiOS#846] opened 2018-11-20 11:30 UTC
### Steps to reproduce

1. Turn off every other filters from AdGuard Pro except YousList
2. Visit <https://www.google.co.kr/amp/www.hankyung.com/news/amp/201811205483v> on Safari
3. `div.atc-ad200`, `aside.amp-md-ad`, `aside.amp-bottom-ad` are visible

### Expected behavior

`div.atc-ad200`, `aside.amp-md-ad`, `aside.amp-bottom-ad` are hidden.

### Actual behavior

`div.atc-ad200`, `aside.amp-md-ad`, `aside.amp-bottom-ad` are visible (but with no content).

[YousList](https://github.com/yous/YousList/blob/master/youslist.txt) has following rules:
```
cdn.ampproject.org##aside.amp-bottom-ad
cdn.ampproject.org##aside.amp-md-ad
cdn.ampproject.org##div.ad
cdn.ampproject.org##div.ad_h100
cdn.ampproject.org##div.adlink
cdn.ampproject.org##div.advertisement
cdn.ampproject.org##div.amp_view_ad
cdn.ampproject.org##div.band_ad_middle
cdn.ampproject.org##div.band_ad_top
www-hankyung-com.cdn.ampproject.org##div.atc-ad200
```
Before specifying `www-hankyung-com.cdn.ampproject.org` for `div.atc-ad200`, it was `cdn.ampproject.org`. See <https://github.com/yous/YousList/commit/b7ffb3d3a38c8b50f3c1b7ae3d68c555c4230c57>. The both before that commit and after that commit, `div.atc-ad200` is not hidden.

Also note that the amp URL is displaying an iframe with src that starts with `https://www-hankyung-com.cdn.ampproject.org/`.

The first screenshot is AdGuard Pro enabled, the second screenshot is 1Blocker X enabled. See the first line of the second paragraph. That's `div.atc-ad200`.
<details><summary>Screenshot:</summary>

![img_1992](https://user-images.githubusercontent.com/853977/48770436-9a0b9280-ed01-11e8-92d7-ccab38d21abd.png)
![img_1993](https://user-images.githubusercontent.com/853977/48770446-a132a080-ed01-11e8-8455-89e1368e9b55.png)

</details>

### Your environment

* Device model and storage size: (e.g. iPhone 6s 64gb) iPhone 7 128GB
* Operating system and version: (e.g. 10.3.1) 12.1
* Browser: (e.g. Safari) Safari
* Wi-fi or mobile internet connection: Both

**Comment by TheHasagi** [comment] 2019-03-22 14:22
Unable to reproduce now. Will be reopened if necessary.

**Comment by yous** [comment] 2019-03-23 07:38
It's still reproducible, but the original site has changed their layout, so one more example:

1. Turn off every filters from AdGuard Pro
2. Add `www-hankyung-com.cdn.ampproject.org##aside.amp-bottom-ad` to custom filters
3. Visit <https://www.google.co.kr/amp/www.hankyung.com/news/amp/2019032365157> on Safari
4. At the bottom, `aside.amp-bottom-ad` is visible
5. Visit <https://www-hankyung-com.cdn.ampproject.org/v/www.hankyung.com/news/amp/2019032365157?usqp=mq331AQECAEoAQ%3D%3D&amp_js_v=0.1#origin=https://www.google.co.kr&cid=1&prerenderSize=1&visibilityState=visible&paddingTop=32&history=1&p2r=0&horizontalScrolling=0&csi=1&storage=1&viewerUrl=https://www.google.co.kr/amp/www.hankyung.com/news/amp/2019032365157&referrer=https://www.google.co.kr&cap=navigateTo,fragment,handshakepoll,cid,replaceUrl> (which is the `src` of iframe in 3) on Safari
6. At the bottom, `aside.amp-bottom-ad` is hidden

I think AdGuard Pro doesn't hide elements inside iframes. The first screenshot is of the site specified on 3, the second screenshot is of the site specified on 5.

<details><summary>Screenshot:</summary>

![IMG_2648](https://user-images.githubusercontent.com/853977/54863232-7fb5f400-4d89-11e9-92a7-4472e2bf3605.png)
![IMG_2649](https://user-images.githubusercontent.com/853977/54863235-8ba1b600-4d89-11e9-9edf-32aff3fdbff1.png)

</details>

**Comment by ameshkov** [comment] 2019-03-23 08:46
@yous as I recall, there were some strange issues with iframes and Safari content blocking API. I'll try to find the original issue.

What if you add `google.co.kr##aside.amp-bottom-ad ` instead, will it work?

**Comment by ameshkov** [comment] 2019-03-23 08:55
Ah, I found it (and it is about AMP websites versions as well):
https://github.com/AdguardTeam/AdGuardForSafari/issues/105

The only solution we can use is to change the rules conversion algorithm and use `url-filter` regular expression for matching cosmetic rules, but that would be VERY SLOW.

**Comment by ameshkov** [comment] 2019-03-23 08:55
Closing this one as duplicate https://github.com/AdguardTeam/AdGuardForSafari/issues/105

Please comment there if you have any ideas.

**Closed by ameshkov** 2019-03-23 08:55 UTC

**Comment by yous** [comment] 2019-03-23 10:02
Thanks for the notice! Adding `google.co.kr##aside.amp-bottom-ad` works, but it can be too general and rules will spread to many sites when I add rules for all iframes.
