### ISSUE TITLE
Extra languages cause iOS/iPadOS "General" content blocker to overflow

### ISSUE THREAD

**Issue by WoodpeckerBaby** [AdguardTeam/AdguardForiOS#1825] opened 2021-09-30 08:36 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

AdGuard - "General" content blocker has an overflow issue

<details>

![IMG_4428](https://user-images.githubusercontent.com/14303318/135415797-ba47c010-c5ac-4a74-8fff-6cb11373bca8.PNG)

</details>

### Proposed Solution

Split regional language filters to an independent content blocker container. The example above only contains one additional language - Chinese, and it is overflowing. If I were to add French and Japanese on top of that, it would simply not work properly. 

### Alternatives Considered

Separate Annoyance related to a different content blocker container. 

### Additional Information

Also, consider making language filter lists in AdGuard settings indexable by language. The '#lang:xx' tag can't be searched in the search box.

**Comment by zeezeepiggy** [comment] 2021-10-01 09:26
Please see this:

https://github.com/AdguardTeam/AdguardForiOS/issues/1583

I requested it before but they won’t do it due to integrity of the rules.

**Comment by WoodpeckerBaby** [comment] 2021-10-02 07:05
Okay, then make the lists self-contained or add another set for the basics. The problem of overflowing doesn't change.

**Comment by Birbber** [comment] 2021-10-04 08:07
@WoodpeckerBaby Hi!
Will close this issue as a duplicate of [1235](https://github.com/AdguardTeam/AdguardForiOS/issues/1235).

**Closed** 2021-10-04 08:08 UTC
