### ISSUE TITLE
Backup icloud

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardForiOS#2278] opened 2024-01-15 23:02 UTC
Hi, using last iOS version of Adguard Pro In icloud i can't found adguard app. How to enable icloud backup?

Or is there a way to export ALL setting?

**Comment by michael1900** [comment] 2024-01-15 23:36
Why after 8 years adguard for iOS still haven't a real backup/restore feature? Why we can't sync with icloud?

8 years, but are you serious?

**Comment by Versty** [comment] 2024-01-16 09:11
@michael1900 The AdGuard for iOS application is currently in the process of code refactoring. We would certainly love to add sync with iCloud feature in the future versions. 

Duplicate of https://github.com/AdguardTeam/AdguardForiOS/issues/479

**Closed** 2024-01-16 09:13 UTC
Labels: Question, Priority: P4
