### ISSUE TITLE
Filters and Whitelists

### ISSUE THREAD

**Issue by lrevenden** [AdguardTeam/AdguardForiOS#1114] opened 2019-07-08 22:16 UTC
Unable to add items to my Whitelist - I’ll add an item then come out of the app, when I go back in the item is missing. The only way I can add to the whitelist now is to edit a text file and import it.
Similar error with the filters, I select or deselect the ones I want then come out of the app but when I go back they have gone back to how they were before I made the change. I have no workaround for this

**Comment by ameshkov** [comment] 2019-07-10 19:39
Duplicate of #1062, it will be resolved in upcoming v3.0.1

**Closed by ameshkov** 2019-07-10 19:39 UTC
