### ISSUE TITLE
Whitelist does not work

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1097] opened 2019-07-03 06:45 UTC
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: (e.g. iPhone 6s 64gb)
* Operating system and version: (e.g. 10.3.1)
* Browser (e.g. Safari)
* Wi-fi or mobile internet connection

**Comment by ameshkov** [comment] 2019-07-03 11:00
Duplicate of https://github.com/AdguardTeam/AdguardForiOS/issues/1062

**Closed by ameshkov** 2019-07-03 11:00 UTC

**Comment by Quorum75** [comment] 2019-07-03 13:19
This was an error but I could not delete the post. Sorry.
