### ISSUE TITLE
VPN is always busy in connecting when enabling AdGuard Protection.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#657] opened 2018-02-14 15:53 UTC
Hi,

VPN was always busy in connecting after enabling AdGuard Protection when the bug occurred.
There is no internet during the process.
After disabling AdGuard Protection, the internet was back.
I have to reboot my iPhone for normal AdGuard VPN connection.
I just recorded the video when the bug again occurred in AdGuard Pro beta v2.0.0(132).
https://youtu.be/2bldYPGtp8U

Yes, I first found the critical bug and ever reported the bug in the past.
https://github.com/AdguardTeam/AdguardForiOS/issues/524
But the original post is behind many posts, and I think the critical bug is forgotten.
So I anew post an issue.
[ I decide to keep this latest one and close that (#524) due to a duplication. ]

From the past until now, the bug still exists.
Sorry that I don't have sure reproduction steps.

I also have sent the bug report around 23:30 (GMT+8) on 14th February, 2018.

User ID: 1425202
Subject: [AdGuard Pro for iOS] bug report

**Comment by Alex-302** [comment] 2018-02-14 15:56
The same issue. Internet is not working during this process.

**Comment by camelot-sun** [comment] 2018-02-14 22:08
I actually have this issue but not only for AdGuard, but also for other VPN apps i used ~ Fsecure Freedome, PIA, VPN.AC

It happens when I am connected to a hotspot or pocket wifi with custom settings . The VPN apps will not connect at all or just say connecting....

It rarely happens though. We debug it, check logs and there seems to be an issue with the CORE.

We reported it to apple to check as the problem seems to be in the CORE( one of the network functions inside the ios, we think has bug).

Also, thanks for creating this issue for tracking, but if there is an existing one, like you mentioned, no need to create a new one. Probably just update the old issue with new details as Git will trigger a notification when an issue is updated.

**Comment by lancelot-moon** [comment] 2018-02-15 04:10
I also ever doubt that it's maybe iOS bug.
But other real VPN apps and adblock could successfully establish VPN connection in such situation when AdGuard Pro met the issue and failed to establish VPN connection.
I'm not a specialist in this territory.
Just report as a tester for their reference.

**Comment by camelot-sun** [comment] 2018-02-15 06:39
It’s alright. Leave this open and let the team handle it. 

I will report back if i hear something from my own team about the bug we reported to apple since it’s related to VPN which is potentially related to the above as well.

Goodluck to us.

**Comment by lancelot-moon** [comment] 2018-02-15 07:41
16th February is Chinese New Year.
Happy Chinese New Year to everyone.

Go to sleep.
Don't worry.

I believe that the new AdGuard Pro will be must smoothly released since it's our common hope!

**Comment by akmLaVx** [comment] 2018-02-16 06:20
As reported by user 1425202,

> Hi,
> 
> I tested AdGuard Pro beta v2.0.0 (132).
> 
> I deleted a subscription and then add a new subscription.
> Afterwards, I clicked "check for updates" for Safari.
> When I enabled the local VPN, the VPN always showed "connecting".
> So there is no internet connection when the bug occurred.
> 
> After disabling AdGuard VPN, my internet connection was back.
> (I only use Wi-Fi because there is no sim card in my iPhone.
> I am not sure if the issue will also occur in cellular network.)
> 
> Sorry, I don't have sure reproduction steps.
> 
> The issue is the same with what I already reported in the past.
> https://github.com/AdguardTeam/AdguardForiOS/issues/524
> 
> B/R

Logs attached.
[jun-xian_yu_adgIosProLogs.zip](https://github.com/AdguardTeam/AdguardForiOS/files/1730390/jun-xian_yu_adgIosProLogs.zip)

**Comment by lancelot-moon** [comment] 2018-02-16 06:29
@akmLaVx

Sir, may you not write my Asian name as the file name?
It's about my privacy.
You can use my user name, Lancelot-moon.
Thanks.

**Comment by akmLaVx** [comment] 2018-02-16 06:30
@lancelot-moon 

Hello!
I've removed any and all mentions of your name.
Sorry for the inconvenience!

**Comment by zebrum** [comment] 2018-02-20 10:14
@lancelot-moon can you also collect iOS logs too?
with any of this tool:
- win: http://help.testlio.com/testing-with-testlio/how-to-get-attachments-for-your-bug-report/how-to-get-ios-logs-on-windows-pc
- mac: https://lemonjar.com/iosconsole/

**Comment by lancelot-moon** [comment] 2018-02-20 10:23
But I already updated to AdGuard Pro beta v2.0.0(136).
I also ever cleared statistics and DNS Requests Log.
Are those log still remained?

**Comment by akmLaVx** [comment] 2018-02-20 13:09
@lancelot-moon I apologize for the inconvenience. Archive has been updated.

**Comment by zebrum** [comment] 2018-02-20 15:13
@akmLaVx you can just post here ticket id and we'll find logs.

@lancelot-moon does the issue persist on .136 build?

**Comment by lancelot-moon** [comment] 2018-02-20 15:34
First, the issue isn't easy to reproduce.
From v1.x.x to beta v2.0.0, the issue always exists.

When I meet the issue again in v2.0.0(136) or next beta version, I'll collect it.

Since I constantly suffered from Sailor-Chibimoon's harassment, no AdGuard administrator forbade him commenting on AdGuard GitHub.
I must reported abuse to GitHub Support by myself.
I'm disappointed at AdGuard team.
Please don't let him again and again harass me!

**Comment by zebrum** [comment] 2018-02-21 09:12
@lancelot-moon ohhh, come on! Don't start it again, please. I think one of you should be wiser. Don't you think that nobody wants to read that hassel?

**Comment by ameshkov** [comment] 2018-02-21 09:33
Offtop: I've said that in another thread, I'll keep an eye on that.

**Comment by lancelot-moon** [comment] 2018-02-21 10:05
Nobody wants hassle.
Just the spy from Future Mind.
GitHub Support told me that you administrator has the right to forbid trouble makers commenting here.
But AdGuard administrator did nothing, except for deleting comments.
Did you administrator have any active methods for forbidding someone costantly harassing me during the several weeks?
No, I just tell about my thought and fact.
As your translator and tester, you just looked on.
Why can I not feel disappointed?

**Comment by ameshkov** [comment] 2018-02-22 09:14
Guys, please let me know if the issue still exists. If it is, we badly need to check the device logs: https://github.com/AdguardTeam/AdguardForiOS/issues/657#issuecomment-366930558

**Comment by lancelot-moon** [comment] 2018-02-28 08:50
@ameshkov 
@zebrum 

Now, I have got the real-time log by iTools.
Where can I send the log to you?

**Comment by zebrum** [comment] 2018-02-28 09:02
send it to support@adguard.com and post here your ticket_id from support.

**Comment by lancelot-moon** [comment] 2018-02-28 10:57
@ameshkov

Hi,

I just had sent the 2 real-time logs to support@adguard.com, and your support had replied me that you got them.
**User ID**: 1425202
**Subject**: AdGuard Pro for iOS VPN bug

My device is iPhone 6 Plus.
iOS v11.2.6

It seems that I found the reproduction steps.
I tried for 2 times and successfully reproduced it again.
I am not sure if you can reproduce it.
Reproduction steps:
1. In Advanced Settings, change to "Full-Tunnel" from "Split-Tunnel".
2. Clear DNS Requests Log.
3. Enable AdGuard Pro VPN.
4. The issue of always being busy in connecting to VPN occurred.
(Maybe it would establish the VPN connection or not.)
5. Disable AdGuard Pro VPN if AdGuard Pro could establish the VPN connection.
6. In Advanced Settings, change to "Split-Tunnel" from "Full-Tunnel".
7. Enable AdGuard Pro VPN.
8. The issue of always being busy in connecting to VPN occurred again.

I also recorded the videos:
The video is the same operations with my 2nd real-time log (AG Pro VPN bug_02.txt) which was already sent to you.
https://youtu.be/wNWHXWk57y4

I did more operations.
That's why the size of 2nd real-time log (AG Pro VPN bug_02.txt) is big.

After the issue occurred with AdGuard Pro, I tried AdBlock by Future Mind and other real VPN apps.
AdBlock by Future Mind could establish the VPN connection at that time.
And then there is some strange trouble with real VPN apps.
Certain VPN apps had the VPN connection trouble.
Maybe it couldn't normally load its servers page in app.
Or it showed an error after I chose a VPN server, but it actually had established the VPN connection.
After I tried those real VPN apps, AdGuard Pro could sometimes establish the VPN connection, but was sometimes still fail to connect to VPN (busy in connecting or simply disconnect).

After the issue occurred, I re-booted my iPhone and did my reproduction steps.
The issue occurred again.
https://youtu.be/-zi6J3K1JRA

Hope that you can find the cause this time!
iOS bug or AdGuard Pro bug?

B/R

**Comment by bigdargon** [comment] 2018-02-28 12:45
Same issue!

**Comment by IvanIin** [comment] 2018-02-28 12:49
@lancelot-moon 
In the logs I see that the tunnel was terminated due to the memory limit exceeded. Perhaps you have too many rules in the privacy module.

**Comment by lancelot-moon** [comment] 2018-02-28 13:06
Although I set many rules in AG Pro beta v2.0.0(140) now, I can normally enable AG Pro VPN in general situation.

I'll reduce my rules and try again.

I think the main cause is not due to many rules in Subscriptions.

iPhone 6 Plus has less RAM.
How about trying my reproduction steps on iPhone X, 8 or 7, even iPad?

**Comment by bigdargon** [comment] 2018-02-28 13:42
@IvanIin I use iphone 6s plus, and my ipad air 2 same issuse. I will send log form my ipad.
![d60a2cde-789b-4ece-b5b9-54067b64eefa](https://user-images.githubusercontent.com/10969626/36790581-e8e3e87c-1cc7-11e8-81fa-936eafdb4749.jpeg)

**Comment by ameshkov** [comment] 2018-02-28 15:25
That is A LOT

**Comment by ameshkov** [comment] 2018-02-28 15:26
Guys, could it be that this problem is caused by the tunnel memory limit? If so, we can mark it as a duplicate of #616

**Comment by bigdargon** [comment] 2018-02-28 15:32
I removed lists by Disconnect, VPN working!

**Comment by lancelot-moon** [comment] 2018-02-28 16:21
If I don't do my reproduction steps, AdGuard VPN is normally working even if clicking "Check for Updates".
Why can I normally use AdGuard VPN with a lot of rules as long as I don't do my reproduction steps?

1. With 97810 rules in privacy setting, AdGuard VPN is normally working from the beginning.
After my reproduction steps, AdGuard VPN was abnormal.
https://youtu.be/QXIzhg5e1uU

2. Following on from the above, I removed AdGuard SDN filter.
With 79551 rules, repeat my reproduction steps, and AdGuard VPN was still abnormal.
https://youtu.be/W32Oa9VC85o

3. Following on from the above, I removed 1hosts.cf filter and then re-booted my iPhone.
With 19555 rules, AdGuard VPN is normally working.
https://youtu.be/3mQiWV73Jeo

**Comment by lancelot-moon** [comment] 2018-03-03 02:59
@ameshkov 
@IvanIin 

Sir,
The issue occurred again in AG Pro beta v2.0.0(140).
Finally, I got the real-time log for AG Pro VPN with only 28.7k rules in privacy setting.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/2EOdIxz.png)
</details><br/>

I sent the bug report at 10:42 AM on 3rd March, 2018. (GMT+8)
The attachment, AG VPN bug.txt, is the real-time log by iTools.
Other attachments are the default logs for the bug report.

I don't have reproduction steps.
I just added/deleted subscriptions and chose a different regular DNS server.
And then the issue occurred.

The video:
https://youtu.be/mmPFH-QvSIg

Hope that you can find the cause.

B/R

**Comment by lancelot-moon** [comment] 2018-03-03 05:34
For the topic, we need to solve 2 issues.
**1. VPN is always busy in connecting due to large numbers of rules and my reproduction steps when enabling AdGuard Protection.**
Even if AG Pro with large numbers of rules can normally enable AdGuard Protection after clicking "Check for updates", AG Pro will be failed to connect to VPN according my reproduction steps.
https://github.com/AdguardTeam/AdguardForiOS/issues/657#issuecomment-369203945

Well, the solution is reducing rules in privacy setting.
How will you warn users if there're too many blocking lists added?
May you first tell us? Please...
Honestly, using large numbers of rules is a kind of romance. XDD
It's so cool!
I can normally enable AG Pro Protection with 90k+ rules as long as I don't do some steps which break down VPN tunnel.
So I don't want AdGuard team to forcefully set a lower upper limit of rules in privacy setting.
If so, it will let me feel difficult.

https://github.com/AdguardTeam/AdguardForiOS/issues/631
Are there any good ideas?

2. **VPN is always busy in connecting due to another critical VPN bug when enabling AdGuard Protection with only a few rules.**
https://github.com/AdguardTeam/AdguardForiOS/issues/657#issuecomment-370111397

Thanks for your hard working!

**Comment by lancelot-moon** [comment] 2018-03-03 09:09
Because I don't know when I can again meet the issue, I still don't re-boot my iPhone.
So my iPhone keeps the status of disconnecting from Wi-Fi while enabling AdGuard Pro Protection.

Do AdGuard team need me to do any tests or save certain logs?
AdGuard team can early contact with me.
If unnecessary, I'll re-boot my iPhone for letting AG Pro become normal...

**Comment by akmLaVx** [comment] 2018-03-03 19:33
Additional logs have arrived for this case. They are available under customer ID 1425202.

**Comment by lancelot-moon** [comment] 2018-03-07 22:21
In beta v2.0.2(146), the bug still exists.
With only 18k+ rules, it disconnected from Wi-Fi when enabling AG Pro Protection.
Just a report.

https://youtu.be/7A8hQ1L9xTY

**Comment by LaxusiC** [comment] 2018-03-09 14:01
Same issue, can not believe this bug still exist after we reported multiple times

**Comment by lancelot-moon** [comment] 2018-03-12 09:24
It's off OR busy in connecting.
2 situations!
Just it's usually busy in connecting.
When the issue occurred...
With 28k+ or 13k+ rules, the real-time log by iTools was early sent to you.

Finally, it's only 18k+ rules.
Please do not say it's because lack of memory due to large numbers of rules.
Do you think 18k+ are large numbers?

**Comment by lancelot-moon** [comment] 2018-03-12 09:27
I sent the bug report at 10:42 AM on 3rd March, 2018. (GMT+8)
User ID: 1425202
Subject: [AdGuard Pro for iOS] bug report
The attachment, AG VPN bug.txt, is the real-time log by iTools.
Other attachments are the default logs for the bug report.

**Closed** 2018-05-14 08:59 UTC
Labels: Bug, Waiting For Data
