### ISSUE TITLE
Widget “unable to load”

### ISSUE THREAD

**Issue by BaronKrause** [AdguardTeam/AdguardForiOS#2017] opened 2022-07-07 17:29 UTC
### Issue Details

- **AdGuard version:**
  AdGuard for iOS v4.4.0
- **Device model and storage size:**
  iPhone 11 256gb
- **Operating system and version:**
  iOS 15.5

### Expected Behavior

Widget loads and shows blocked content and toggles for enabling or disabling AdGuard blocking.

### Actual Behavior

Widget shows “unable to load” message

### Screenshots

<details><summary>Screenshot:</summary>

![00804A3A-AC99-46AC-B458-BFA6C60117CD](https://user-images.githubusercontent.com/16513453/177832536-65a10321-0d3b-4e21-b238-f24a91b04b61.jpeg)

</details>

### Additional Information

I have been using AdGuard beta via TestFlight with a paid unlimited account for over a year on iPhone and iPad and for a while the widget has been busted only showing “unable to load”. A few months back I noticed an update seemed to have fixed it on iPad, but on my iPhone it is still broken.

To help troubleshoot this I tried fully removing it and testing the stable version, with the same result. And to make things even worse, when I went to go reinstall the TestFlight, it seems it’s no longer in the list, like uninstalling and installing the stable version removed it, and it’s no longer open to new people.

The widget has always been a little buggy but this just seems weird, the phone has no issues with any other widgets either.

I have seen others on Reddit complain about it but it seems mixed, which I can attest to given one of my devices has a perfectly working widget.

I’d be happy to help with any other information if needed.

**Comment by Versty** [comment] 2022-07-08 10:37
@BaronKrause Hi! 

Thank you for the detailed description. TestFlight AdGuard builds currently unavailable for everyone due to planned changes. You could use the release version from the App Store until test builds return soon.   

We tried to reproduce this issue on our devices but widget works fine.
That is why to troubleshoot unusual behaviour we would like to get the app logs from your device.

Please follow the steps above:

1. Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
2. Reproduce the issue (delete and add the widget back) and remember the exact time when it happened;
3. Open the settings --> Support --> Export logs;
4. System popup will be opened --> Choose "Mail" app;
5. Enter [apple@adguard.com](mailto:apple@adguard.com) as a recipient;
6. Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by Versty** [comment] 2022-07-19 08:22
@BaronKrause Hi! 

We have examined the logs and seems to be you have found a bug. We are taking this case to work and will do our best to fix the issue in the next major release.

**Comment by rakleed** [comment] 2022-07-22 12:57
@Versty isn't this a duplicate of https://github.com/AdguardTeam/AdguardForiOS/issues/1849?

**Comment by Versty** [comment] 2022-07-22 13:14
@rakleed Yes, you're right. 
@BaronKrause Closed as duplicate.

**Closed by Versty** 2022-07-22 13:14 UTC
Labels: Bug, Duplicate, Resolution: Duplicate, Priority: P4, Version: ADGuard v4.6 [Reserved], Status: Done
