### ISSUE TITLE
Error while loading filters into Safari

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#550] opened 2017-12-13 13:57 UTC
Since there are a lot of such errors, let's have a task. Probably iOS bug
### Steps to reproduce

1. Load new filters or UF into Safari

### Expected behavior

Filters are loaded correctly

### Actual behavior

<details><summary>Screenshot:</summary>

![img_0001](https://user-images.githubusercontent.com/23637588/33942000-98d5db9e-e025-11e7-9511-25cb29063b1c.png)

</details>

Possible solution: swipe Safari to close it and restart AG.

### Your environment

* Browser: Safari

**Comment by vozersky** [comment] 2017-12-13 14:10
have to get an iOs console log

**Comment by Goddess-Bastet** [comment] 2017-12-14 12:51
I have the same bug on my iPhone X, 5s & iPad Pro 9.7.

**Comment by ameshkov** [comment] 2017-12-17 16:48
@zebrum do we know any stable way to reproduce this?

**Comment by BlazDT** [comment] 2017-12-20 02:03
Application version: 1.3.3.89
Device: iPhone
Platform: iOS
OS: 11.1.2

Helpdesk ID: 1108721

According to customer "Another issue is that switching on and off AdGuard several times shows an error message."

**Comment by zebrum** [comment] 2017-12-20 11:53
@ameshkov yes, we do. You just need to load filter or several filters into Safari.

**Comment by IvanIin** [comment] 2017-12-29 13:37
`Dec 29 16:31:04 Adg-iPhoneX kernel[0] <Notice>: EXC_RESOURCE -> com.apple.SafariServices.Content[8803] exceeded mem limit: ActiveSoft 150 MB (non-fatal)
Dec 29 16:31:04 Adg-iPhoneX kernel[0] <Notice>: 476630.614 memorystatus: killing_highwater_process pid 8803 [com.apple.SafariServices.Content] (highwater 3) - memorystatus_available_pages: 26612
Dec 29 16:31:04 Adg-iPhoneX Adguard Pro[8789] <Notice>: (AEService) Finishing notify Safari - reloadContentBlockerWithIdentifier.`

com.apple.SafariServices.Content process killed by the system due to exceeding the memory limit

**Comment by ameshkov** [comment] 2018-01-02 22:18
Basically, we need to find a way to further compress the filtering rules.

This can be solved on the JS rules converter side.

**Comment by lancelot-moon** [comment] 2018-01-13 14:46
This issue also occurred in unreleased AG Pro v2.0.0 (124) while trying to save rules in the user filter or domains in the whitelist for Safari Content Blocker.

In the user filter for Safari Content Blocker:
Error: Filters cannot be loaded into Safari.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/wkfUorC.png)
</details><br/>

In the whitelist for Safari Content Blocker:
Error:  Filters cannot be loaded into Safari.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/JvoqqnC.png)
</details><br/>

B/R

**Comment by ameshkov** [comment] 2018-01-20 08:37
@Mizzick this issue is what I was telling you about the filters compression. Let's try compressing Safari CB more.

**Comment by lancelot-moon** [comment] 2018-01-28 07:43
Today, I just entered Blocking Lists, and then the warning suddenly jumped.
"Filters cannot be loaded into Safari. Try to clear your rules and the whitelist, or change the set of used filters."
Only report.

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/MQdcgdY.png)
</details><br/>

**Comment by zznosar** [comment] 2018-01-28 10:40
This is not related to the Blocking List (as they are not loaded in Safari), but the Safari Content Filters. @lancelot-moon , your Safari Filters probably is "Updating" when you go to the Blocking List.

I have 59K rules in blocking list in my ipod touch and ipad pro.

I don't have this issue in iPad Pro (probably because it's a more powerful device) - I have english, spyware, annoyance, mobiles ads filter in safari content blocker.

In my iPod Touch, I encounter this in Safari Content blocker ~ so I only selected Simplified Domain Filters to mitigate the issue.

**Comment by lancelot-moon** [comment] 2018-01-28 10:50
I knew Blocking Lists is not related to Safari Content Blocking.
Well, I fast entered Blocking List at that time.

Maybe it's due to my old iPhone 6 Plus.
Only have 1GB ram.
｡･ﾟ･(ﾉ∀`)･ﾟ･｡

Anyway, just report.
Please don't mind.

**Comment by zznosar** [comment] 2018-01-28 11:06
@lancelot-moon , you can deselect some filters in the content blocket to prevent this. What I did in my ipod touch(which has also 1gb of ram ) is to deselect everything except Simplified Domain Name filters and mobile ads filter.

As far as i can tell, the limit of rules is 50K, but if the rules is above 40K, it will start to complain with this. If the rules are less than 40K, eg. 35K, it will not complain.

**Comment by lancelot-moon** [comment] 2018-01-28 11:19
Thanks for your reply.

I applied about 45k rules in Safari Content Blocker.

When I just tried to disable a filter, that such warning jumped again.
The change for filters was not loaded.
Maybe it was updating at that time.
Later, I tried again.
The change for filters was saved.

What you will do is the compression of filters.

**Comment by zznosar** [comment] 2018-01-28 11:29
Lets’s wait for the AdGuard Team to find a solution for this as this. This seems to be an issue even with the stable version 1.3.3 due to too many filters selected.

If they cannot compresss it, probably just default to Simplified Domain Filters + Mobile Ads filter since this two filters are very powerful enough in my opinion. If you live in a country e.g Taiwan that has its regions specific filter, you can select the chinese filter as well. Just my opinion though.

**Comment by lancelot-moon** [comment] 2018-01-28 16:22
No, English filter, Spyware filter, Social media filter, Annoyances filter and Safari filter are basic filters for Safari.

SDN filter only can block domains.
Do you think SDN filter can block those elements and pop-ups on pages?
Mobile Ads filter is specially for ads in apps, not for browsers.

Especially, when we enable English filter, Spyware filter, Social media filter, Annoyances filter, Safari filter and localism filter (ex: Easylist China), there are already large numbers of rules.

I don't understand why AdGuard team decided to set Mobile Ads filter as default.

It's better to set English filter, Spyware filter, Social media filter, Annoyances filter and Safari filter as default.

**Comment by zznosar** [comment] 2018-01-28 18:23
Simplified Domain Name filter is a combinatiom of whay you just said and is used by their AdGuard DNS....

Please check their website.

There is no quota on how many filtes you want to select. Only the rules.

The default AdGuard filters - English - Spyware - Social -Annoyance and safari are already big enough. But if a user add one more, then they will encpunter this issue.

It’s just a suggestion if they cannot compress. If this is an apple ios limitation or hardware limitation, the it to hard to fix.

**Comment by lancelot-moon** [comment] 2018-01-28 23:00
I have understood, but you don't understand what SDN filter is.
It's for DNS-level filtering.
It's a simplified filter, not a full combination.
You should open those filters and read the content.
You'll understand the difference.
Do you think SDN filter can block elements and pop-ups on pages?
Those annoyances?
In your opinion, you even think English filter is unnecessary because SDN filter is the combination of those filters.
You just ignore "Simplified".

**Comment by zznosar** [comment] 2018-01-28 23:06
Chill. It’s just a suggestion to mitigate this issue. As mentioned they can still select whatever they want. People do “install and forget”. It’s just defaulting (at first launch). They can still select whatever they want to choose.

Do you have anything that you can think of that can possibly mitigate this issue?

**Comment by lancelot-moon** [comment] 2018-01-29 00:48
Sorry if offending you.
But you should already know SDN filter is not so powerful as what you think because it abandoned those rule syntax.
Especially, SDN fiter and Moble Ads filter can't solve anti-adblock...

SDN filter can't replace English filter, Spyware filter, Social media filter and Mobile Ads filter.

Simply, wait for the result of compression for filters.

**Comment by zznosar** [comment] 2018-01-29 01:32
LOL. I’m alright not offended at all.  Blame it to my Australian english. :-) we sounded weird sometimes, but not all the time!

**Comment by lancelot-moon** [comment] 2018-01-29 10:18
For Safari,
Moble Ads filter has about 1800 rules.
But EasyList China is a big guy, it has about 6200 rules.

Well, there are totally 47134 rules after enabling English filter, Spyware filter, Social media filter, Annoyances filter, Safari filter, Mobile Ads filter and EasyList China filter...

**Comment by zznosar** [comment] 2018-01-29 10:21
@lancelot-moon you are almost at your limit mate. you will encounter issues for sure... especially when you reach 50K

**Comment by XCoderever** [comment] 2018-01-31 07:23
I wrote an email and they said they were fixing it... but no changes. How long has this been going on?

**Comment by Sailor-Chibimoon** [comment] 2018-01-31 19:14
I am here to report the same issue. I am using iPhone 7 Plus. As mentioned by the previous I deselected some filters. It stopped from appearing. I have a total count of 39K + rules

**Comment by ameshkov** [comment] 2018-02-01 20:30
Here's an update on this.

It appears that the issue is caused not just by some per-process memory limit, but by the limit on the free RAM on a device. They've changed the content blocker compilation process in iOS 11.2 and due to that, the whole "compile & load" process is failing much more often.

There's more to it. On AdGuard's side a memory intensive "adguard rules --> content blocker rules" conversion process takes place.

So here's what we should do:

1. Do not trigger loading filters to Safari until the memory used for conversion is freed up;
2. Change the server-side optimization process so that the default set of filters was smaller;

**Comment by ExpertContributor** [comment] 2018-02-06 14:08
The following solves (works around) the issue for me:

1. Settings ➡️ Safari ➡️ Content Blockers ➡️ AdGuard 📴
2. Perform action with AdGuard (update/load or unload filters/block object) 
3. Return to settings as before and switch it ✅ on.
4. Close Safari and then reopen it 

This works regardless of how many filters I have, and the number of filters does not appear to alter the frequency of the errors occurring.

The presence of other ad blockers also appears to be irrelevant, as does the presence of an active VPN.

DNS logs shine no light on the issue either.

**Comment by ameshkov** [comment] 2018-02-06 15:40
@IvanIin let's close this issue once the part 1 is resolved. It partly solves it, and the filters optimization will be addressed on the server side.

Also, I need you to prepare a simple iOS content blocker extension with 50k rules JSON that we can use to report this bug to Apple.

**Comment by kathampy** [comment] 2018-02-16 10:17
The workaround is to disable the Content Blocker, update the filters in AdGuard, and enable the Content Blocker again. Otherwise the error occurs 100% of the time.

**Comment by evgeniy-ADG** [comment] 2018-02-17 16:59
@kathampy AFAIK it doesn't load updates to Safari when you're doing so, you just avoid the error messages but the rules remain not updates. But if you unload both AdGuard and Safari from the memory, open AdGuard and check updates, it might work.

**Closed** 2018-02-22 08:59 UTC
Labels: P2: High, iOS Bug

**Comment by lancelot-moon** [comment] 2018-03-01 10:31
@ameshkov 

Sir,
Abnormal large numbers of rules occurred in my Safari filters.
I just enable English filter, Spyware filter, Social media filter, Annoyances filter, Safari filter and EasyList China filter.
But it shows that there are 85061 rules enabled and 50000 active rules.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/UYKvYgL.png)
</details><br/>

**Comment by ameshkov** [comment] 2018-03-01 10:33
@lancelot-moon wait a bit, optimization algorithm bug on the server side, will be resolved soon

**Comment by lancelot-moon** [comment] 2018-03-01 10:50
Thanks!
I also think if something wrong happened in your server, especially you're updating Safari filters' names and descriptions recently.

Only enable English filter, but it has 57629 rules. XD
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/BpknBL2.png)
</details><br/>

Before I read your reply, I just sent the bug report.
Please ignore it.

B/R
