### ISSUE TITLE
Filters tags disappeared

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForiOS#911] opened 2019-03-05 13:05 UTC
v3.0.0(117)

**Comment by IvanIin** [comment] 2019-03-11 11:55
Fixed in 118.
This is app update error. The bug should not be reproduced with a clean installation of the application or when upgrading from the appstore version(101) to 118 and higher.

**Comment by aspasskaya** [comment] 2019-05-15 15:23
The problem is still exist.
![image](https://user-images.githubusercontent.com/43952607/57787674-808e5500-773e-11e9-8911-0e7ca085fc90.png)

**Comment by ameshkov** [comment] 2019-05-23 11:27
Cannot reproduce with .134

**Closed** 2019-06-25 13:25 UTC
Labels: Bug, P3: Medium, UI
