### ISSUE TITLE
AdGuard fails to load filters when "Filter unblocking search ads..." is enabled

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#1319] opened 2019-10-20 09:15 UTC
<details> <summary> screenshot of the error message </summary>

![image](https://user-images.githubusercontent.com/15856304/67157299-fc667c00-f332-11e9-85e7-23dc0e50d2a5.png)

</details>

<details> <summary> screenshot of the content blocker rules stats </summary>

![image](https://user-images.githubusercontent.com/15856304/67157303-10aa7900-f333-11e9-8384-30d95b78c6a6.png)

</details>

The user who reported the issue, states that the problem persists after reinstalling the app but does not occur when the Filter unblocking search ads and self-promotion is disabled.

**Comment by SoLenny** [comment] 2019-10-21 11:49
@Eugene-Savenko Can't reproduce it my side.
Can you get logs from the user?

**Comment by IvanIin** [comment] 2019-10-28 14:40
this problem has been fixed in task #1263

**Closed** 2019-10-28 14:40 UTC
Labels: Waiting For Data
