### ISSUE TITLE
Keep configurations synchronized across multiple devices and family members

### ISSUE THREAD

**Issue by money-finder** [AdguardTeam/AdguardForiOS#2037] opened 2022-08-03 10:35 UTC
### Problem Description

I have almost 10 devices and it's a pain to synchronize configurations across devices. I have about 70 domains in the exclusions list, so I have to configure them almost a thousand times to synchronize across multiple devices, which is horrible!

### Proposed Solution

I would like to add a personalized configuration profile feature where I can configure DNS filter lists, exclusions lists, etc., so that I can configure DNS filter lists and exclusions lists once in my account, and then log in to different devices in that account to select the corresponding configuration profile and directly achieve Configuration synchronization.

### Alternatives Considered

If you can't add account-level configuration file synchronization, you should at least add a configuration file export feature to facilitate configuration synchronization for multiple device users

**Comment by Versty** [comment] 2022-08-05 15:39
@money-finder Hello! We appreciate your patience and loyalty to our products.
[Here](https://github.com/AdguardTeam/AdguardForAndroid/issues/134) is the same feature request. 
Closed as duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/134.

**Closed by Versty** 2022-08-05 15:39 UTC
Labels: Feature request

**Comment by money-finder** [comment] 2022-08-05 17:00
It's hard to believe that this question was asked back in 2015, but it's not being done now. In my opinion, implementing a minimal profile import and export is better than doing nothing at all. 

Of course I would like the system to add the feature of a configuration profile directly for the account, after all it is a basic feature for a multi-device user.

**Comment by Versty** [comment] 2022-08-09 08:41
@money-finder Available settings differ from one platform to another, so we've postponed the synchronization implementation. But if you are configuring several devices on the same Windows, macOS, Android platform or browser extension, you can use the settings export option, which already exists. Except for the iOS, where import/export option will be implemented soon enough.
