### ISSUE TITLE
On the iOS 15.4 beta the manual update spinner just keeps on spinning

### ISSUE THREAD

**Issue by ArttuLai** [AdguardTeam/AdguardForiOS#1926] opened 2022-02-04 21:35 UTC
### Issue Details

- **AdGuard version: TestFlight beta 4.3.2 (937)**
- **Device model and storage size: iPhone 12 Pro Max 128GB**
- **Operating system and version: iOS 15.4 beta 1**

### Expected Behavior

When I press the manual update button on the top right corner, it should update the filters, notify, and stop spinning.

### Actual Behavior

It just keeps on spinning indefinitely, and has done that since I installed iOS 15.4 beta a week ago. However, my filters are up-to-date, not sure if the manual update actually works or that it's updating them in background successfully.

### Screenshots

<details><summary>Screenshot:</summary>

![6C751362-7FC3-47E4-B380-25171BF89C98_1_201_a](https://user-images.githubusercontent.com/42007282/152605886-b8862835-334c-4ff8-8e47-adcbc7c71ca2.jpeg)

</details>

### Additional Information

I tried the TestFlight (several older versions) and App Store version and both have this same issue. My internet works just fine. I know iOS betas can introduce some weirdness that gets fixed on its own in due time, but I thought I'd give a heads up.

**Comment by ameshkov** [comment] 2022-02-05 14:15
We're aware of the issue, but we're waiting for a newer iOS beta to get out. At this moment it looks like a bug in iOS (and we've already reported it to Apple).

It seems that the actual underlying issue is that this update messes with Safari content blockers state. Try going to Safari settings and disable them all, then enable them back again. You may need to forcibly close both AdGuard and Safari after that and wait a little.

**Comment by ameshkov** [comment] 2022-02-05 14:16
I've assigned it to v4.4 just in case so that we didn't forget to re-test it when the new iOS beta is out.

**Comment by tosbsas** [comment] 2022-02-08 16:24
Must be 15.4 problem as in 15.3 its just Fine. Turning all off and on of Blockers won't fix it

**Comment by ameshkov** [comment] 2022-02-08 16:42
> Turning all off and on of Blockers won't fix it.

It actually fixed it on my test device, but I did it a couple of times.

**Comment by tosbsas** [comment] 2022-02-08 16:46
Ok. Let me know step by step 

I killed both apps 
Disabled extensiones 
Enabled extensión 
Started AdGuard pro - pressed Update and got a nonstop Update Circle 




______________________________
Ruben Gutknecht
Lima, Perú  🇵🇪 
Cel: +51-99349-1515
Voice/Fax: 49 (0) 721-151-379204
http://telegram.me/tosbsas
paypal.me/RubenGutknecht
***@***.***

**Comment by ameshkov** [comment] 2022-02-08 17:42
Just a quick check: could you please try disabling advanced protection in AG and restart it? Does it change anything?

**Comment by tosbsas** [comment] 2022-02-08 17:45
No change

**Comment by tosbsas** [comment] 2022-02-08 17:47
Wierd though - Advanced Protection enables itself as soon as I press the Update Filter Button

**Comment by tosbsas** [comment] 2022-02-08 17:53
Now it worked :-) and Update went thru. What do I do next :-)

**Comment by ameshkov** [comment] 2022-02-08 17:57
Well, we'll need to file one more bug report to Apple it seems.

We can add a workaround for this one, but I'd prefer to wait for the next beta, the bugs we're encountering are rather serious, I think Apple should fix it before releasing the update.

**Comment by tosbsas** [comment] 2022-02-08 17:58
Ok :/) 

Ruben 




______________________________
Ruben Gutknecht
Lima, Perú  🇵🇪 
Cel: +51-99349-1515
Voice/Fax: 49 (0) 721-151-379204
http://telegram.me/tosbsas
paypal.me/RubenGutknecht
***@***.***

**Comment by tosbsas** [comment] 2022-02-08 18:08
New dev beta is out so lets see :-))


_______________________________
Ruben Gutknecht
Lima, Peru
Cel: +51-993491515
Voice/Fax: 49 (0) 721-151-379204 
http://telegram.me/tosbsas
Threema ID: SPEAJUP9
PayPal.me/RubenGutknecht
Deutschland
***@***.***
***@***.***

**Comment by tosbsas** [comment] 2022-02-08 19:31
Beta 2 does Not fix it

**Comment by fenderwhite** [comment] 2022-02-09 01:28
> This is a consequence of the initial bug.
> 
> Please try disabling AdGuard Base filter just in case and see if it changes anything.

Thx.

Now I only abled
- AG Mobile Ads filter
- List-KR (Korean filter)
- YousList (Korean filter)
- Native DNS protection(Cloudflare Secure)
- Advanced protection
and the update works properly.

If I enable AG Base filter or AG Annoyances filter, the update never stops.

Anyway, I think I can use AG for now. :)

**Comment by ArttuLai** [comment] 2022-02-09 05:09
15.4 beta 2 does not fix it. I’ve tried disabling suggested filters (AG base and annoyances) and toggling content blockers off and on, but I still get The Spin.

**Comment by ameshkov** [comment] 2022-02-09 09:05
Hm, I can't update to it yet

**Comment by ameshkov** [comment] 2022-02-15 19:55
Fixed by https://github.com/AdguardTeam/AdguardForiOS/commit/9eb5f8a6c83232ff7f91838581553b0cc09b1332

We had to resort to some workaround solution just in case Apple does not resolve this in newer betas.
The fix will be available in v4.3.3 beta.

**Closed by ameshkov** 2022-02-15 19:55 UTC
Labels: iOS Bug, Compatibility, Resolution: Fixed, Status: Resolved, Version: AdGuard v4.3.3

**Comment by Yoshiki93** [comment] 2022-02-18 00:26
Ios 15.4 beta 3 doesn’t seems to be fixed. Using AG 4.3.2 pro currently.

**Comment by Yoshiki93** [comment] 2022-02-18 10:04
How to update to 4.3.3? Im not a beta tester. 🥺

**Comment by ameshkov** [comment] 2022-02-20 10:24
@Yoshiki93 the beta program for AG is open: https://adguard.com/beta.html

For AG Pro it is generally not open, but for now, you can use this link to join (will be working for a couple more weeks): https://testflight.apple.com/join/XsivGQq5

**Comment by Yoshiki93** [comment] 2022-02-21 07:38
@ameshkov so far v4.3.3 (940) works as intended! 👍
