### ISSUE TITLE
Internet doesn’t work on Cellular data when DNS filtering is turned on and an Encrypted DNS filtering service is selected. 

### ISSUE THREAD

**Issue by Roshanalexander** [AdguardTeam/AdguardForiOS#677] opened 2018-03-03 01:55 UTC
### Steps to reproduce

1. Enable DNS Filtering.
2. Turn off WiFi
3. Observe webpages doesn’t load on safari until WiFi turned on. ( Webpages will load on Cellular data if DNS filtering is turned off).

### Expected behavior

Should be able to use internet and visit websites on cellular data when DNS filtering is turned on. 

### Actual behavior

Websites doesn’t load on Cellular data when DNS filtering is turned on. No matter which DNS server is used. 

<details><summary>Screenshot:</summary>

</details>

### Customer ID 

1777447

### Your environment

* iPhone X
* iOS 11.2.6
* Safari
* Mobile internet connection
* Carrier: T-Mobile

**Comment by lancelot-moon** [comment] 2018-03-03 03:47
For the issue, when you switch internet connection from Wi-Fi to cellular network, you need to restart AdGuard Pro VPN.

Otherwise, AdGuard team must design that AdGuard Pro will automatically re-connect when users switch the internet connection between Wi-Fi and cellular network.

**Comment by zznosar** [comment] 2018-03-03 05:56
OK. You are in T-MOBILE which hijacks DNS. 

There is an open issue in AdGuard DNS about this:
https://github.com/AdguardTeam/AdguardDNS/issues/202

and also in reddit:
https://www.reddit.com/r/Adguard/comments/6wejit/is_it_no_longer_possible_to_do_systemwide/
and here as well:
https://www.howardforums.com/showthread.php/1885858-DNS-Hijacking

I believe the issue is your service provider.
Here in Australia, most of ISP hijack DNS so we use port 5353 (as suggested by AdGuard) or we use DNSCrypt. DNSCrypt will be included in v2.0 which will be released soon. That hopefully fixes your issue.

**Comment by lancelot-moon** [comment] 2018-03-03 06:24
I think that he was talking about being failed to load page after switching the internet connection between Wi-Fi and cellular network.

I guess that AdGuard DNS setting was for Wi-Fi connection at that time.
Since he turned off Wi-Fi, AdGuard DNS setting lost its internet connection.
However, all network traffic was still routed to AdGuard VPN, and DNS was bound by AdGuard DNS setting which had no internet connection.
Simply, he needs to manually restart AdGuard Pro Protection after switching the internet connection between Wi-Fi and cellular network.

It's not because of DNS hijacking by his ISP in this case.
And then there is another critical bug for AdGuard DNS. 
https://github.com/AdguardTeam/AdguardForiOS/issues/528

https://github.com/AdguardTeam/AdguardForiOS/issues/657 and https://github.com/AdguardTeam/AdguardForiOS/issues/528 are unsettled issues and real challenges for AdGuard team.

**Comment by Roshanalexander** [comment] 2018-03-03 19:09
Hey guys, thanks for your suggestions. 

I'm not entirely sure whose suggestion is right. In my case, when I switch from Wifi to Cellular data, I'm loosing internet connectivity. 

From little troubleshooting, I figured out what's happening:

I'm using an the encrypted AdGuard DNS server which for some reason doesn't work on cellular data.

If I switch my DNS server to the Regular AdGuard Default DNS server, I have no problem with connectivity when I switch between Wifi and Cellular Data.

**Comment by zznosar** [comment] 2018-03-03 21:11
Hmm. That is kinda weird. Mine works perfectly in both wifi and cellular (Optus ISP Australia). Even with my company’s DNS via DNSCrypt, it’s working. Probably T-mobile is blocking the DNSCrypt port? I think it’s better if you send the logs as well to the AdGuard Team so that they can check.

**Comment by ameshkov** [comment] 2018-03-04 10:27
I bet the issue is caused by the ISP -- it might be relying on their own DNS servers.

Needs to be re-tested when version 2.0 is out.

**Comment by Roshanalexander** [comment] 2018-03-04 16:09
@zznosar I tried all DNS servers listed under encrypted DNS servers and none of them works. 

@ameshkov I think it has something to do my carrier Tmobile.

**Comment by ameshkov** [comment] 2018-03-04 20:51
@Roshanalexander

It definitely looks like T-Mobile relying on DNS hijacking in order to provide connectivity to IPv4 servers via IPv6 addresses (that you receive from a hijacked answer).

The only option is to keep using system default DNS and add a blocking list in privacy settings to benefit from the DNS filtering.

**Comment by ameshkov** [comment] 2018-03-16 14:08
Will be handled in #688

**Closed** 2018-03-16 14:07 UTC
Labels: Waiting for repro
