### ISSUE TITLE
Custom DNSCrypt provider - Done button disabled.

### ISSUE THREAD

**Issue by kathampy** [AdguardTeam/AdguardForiOS#684] opened 2018-03-06 09:38 UTC
When adding a custom DNSCrypt provider, the Done button is disabled. I've completed all the fields but the button is still disabled.

I've obtained the fields from the stamp using the following tool: https://dnscrypt.info/stamps/

### Steps to reproduce
1. Choose DNS Settings > Encrypted DNS Servers > Add custom
2. Fill in the fields

### Expected behavior
Should be able to click the Done button.

### Actual behavior
Done button is disabled

<details><summary>Screenshot:</summary>
![img_d3c449a3ab8b-1](https://user-images.githubusercontent.com/3624089/37024653-7605035e-214f-11e8-8f15-c3992c0deca4.jpeg)
</details>

### Customer ID 
1556199

### Your environment
* Device model and storage size: iPhone X 256GB
* Operating system and version: 11.2.6
* Browser: N/A
* Wi-fi or mobile internet connection: N/A

**Comment by IvanIin** [comment] 2018-03-06 09:49
@kathampy you must set the public key in format `D12B:47F2:52DC:F2C2:BBF8:9910:86EA:F79C:E449:5D8B:16C8:A0C4:322E:52CA:3F39:0873`

**Comment by kathampy** [comment] 2018-03-06 09:57
@IvanIin It's accepted the key, but unfortunately it doesn't seem to work over port 443 or TCP.

**Comment by ameshkov** [comment] 2018-03-06 09:58
Duplicate of #685

**Closed by ameshkov** 2018-03-06 09:58 UTC
Labels: Duplicate
