### ISSUE TITLE
Add URLScheme for shortcut

### ISSUE THREAD

**Issue by YuMingChang** [AdguardTeam/AdguardForiOS#2357] opened 2024-07-18 10:13 UTC
### Issue Details

I'm a big fan of using Shortcut to handle chores on my phone, but I found that it only supports turning on/off the DNS protection and complex protection on this repository.

### Proposed solution

Please add the [OpenDnsSettingsControllerParser](https://github.com/AdguardTeam/AdguardForiOS/blob/master/AdguardExtension/AdguardApp/AppDelegate/URLScheme/Parsers/OpenDnsSettingsControllerParser.swift) and [OpenMainPageControllerParser](https://github.com/AdguardTeam/AdguardForiOS/blob/master/AdguardExtension/AdguardApp/AppDelegate/URLScheme/Parsers/OpenMainPageControllerParser.swift) processors into [URLSchemeParser](https://github.com/AdguardTeam/AdguardForiOS/blob/master/AdguardExtension/AdguardApp/AppDelegate/URLScheme/URLSchemeParser.swift).

**Comment by Versty** [comment] 2024-07-22 09:59
@YuMingChang We are currently working on complete code reengineering and have some plans on improving Shortcuts functionality in future versions. Stay tuned!

**Comment by Versty** [comment] 2024-07-22 10:02
Duplicate of #1857

**Closed as completed** 2024-07-22 10:02 UTC
Labels: Feature request, Resolution: Duplicate, Status: Closed, Triage, Priority: P4
