### ISSUE TITLE
When entering whitelist or user filter in the settings of AG for iOS v3 on iPad Pro 11", there are randomly and temporarily flashing vertical white lines on screen.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1248] opened 2019-09-17 11:50 UTC
When going to whitelist or user filter in the settings of AG for iOS v3 on iPad Pro 11", there are randomly and temporarily flashing vertical white lines on screen.

Is this normal?

**Comment by 08kovalchuk03** [comment] 2019-09-18 07:58
@lancelot-moon sounds abnormal, but I can't reproduce it, could you record your screen while lines are flicking?
Could you also provide your IOS version?

**Comment by lancelot-moon** [comment] 2019-09-18 08:27
@08kovalchuk03 

I only see obvious flashing vertical lines when going to whitelist or user filter.
https://youtu.be/8Zq_K9fOA3Y

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/fQsCO0O.png)
</details><br/>

**Comment by IvanIin** [comment] 2019-09-18 12:45
@lancelot-moon 
could you check this bug on build 233?

**Comment by lancelot-moon** [comment] 2019-09-18 13:50
From the beginning, I tested it on testflight v3.1 (233).
It's the same situation.
Temporarily flashing vertical white lines when going to whitelist or user filter.

**Comment by 08kovalchuk03** [comment] 2019-09-20 14:14
fixed in https://github.com/AdguardTeam/AdguardForiOS/issues/1250

**Comment by lancelot-moon** [comment] 2019-09-22 09:19
I uploaded a new video.
It's more obvious.
https://youtu.be/dan7NmtGRqw

Temporarily flashing vertical white lines when **going to or leaving whitelist/user filter**.

**Comment by lancelot-moon** [comment] 2019-09-30 06:55
I tried the latest testflight version on iPadOS v13.1.1.
It seems that you fixed flashing white lines when entering/leaving whitelist and user filter.

**But now flashing white lines appear when entering/leaving "license" in about.**
(I didn't login into my AdGuard account when testing.)

**Closed** 2019-10-02 14:43 UTC
Labels: Bug, Cannot Reproduce, P4: Low, UI
