### ISSUE TITLE
AG Pro randomly crashes when deleting activity log

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1797] opened 2021-07-26 14:30 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AG iOS Beta 4.2.1 (710)
- **Device model and storage size:**
  -  iPhone 11 Pro Max. 
- **Operating system and version:**
  -  iOS 14.7
- **Browser or App:**
  - 

### Expected Behavior

 AG should remain stable when deleting all entries in the Activity section.   

### Actual Behavior

 When you delete the Recent Activity log the application crashes randomly. Maybe 3/5

### Video

</details>

### Additional Information

 Strangely it never happens on my iPad Pro 11 with same iOS and AG Pro versions.

**Comment by anastenko** [comment] 2021-07-26 15:11
@Quorum75 Hello.
We couldn't reproduce it on our end. So please, collect the app logs.

Here's what we need you to do:

- Enable debug logs (Settings --> General --> Advanced settings --> enable Debug logs);
- Reproduce the issue (and remember the exact time when it happened);
- Open the Settings --> Support --> Export logs;
- Send the logs to `apple@adguard.com` and mention this issue number in the email text.

**Comment by Quorum75** [comment] 2021-07-26 18:12
OK

**Comment by anastenko** [comment] 2021-07-27 12:38
@Quorum75 Didn't receive the logs though. Could you resend it please?
Also collect crash info in Settings --> **Analytics and improvement** --> **Analytics data** --> find the needed crash data by date and time and send it to apple@adguard.com

**Comment by Quorum75** [comment] 2021-07-28 08:04
Adguard did receive the email, but it was not open.

I will send it again.

**Comment by zzebrum** [comment] 2021-07-28 13:52
@Quorum75 add me mg@adguard.com to copy please. I'll also check if there is a problem with apple@adguard.com

**Comment by Quorum75** [comment] 2021-07-30 13:06
Email sent just now to To Anastenko and Zzebrum to both emails you gave me. 

Incident time: 2:44pm on July 30th, 2021. 

Thanks for your help.

**Comment by anastenko** [comment] 2021-07-30 13:16
@Quorum75 Thanks, received the logs. Will pass them on to our developers.

**Comment by Quorum75** [comment] 2021-08-16 16:54
> @Quorum75 Thanks, received the logs. Will pass them on to our developers.

Any feedback? Cheers.

**Comment by Aydinv13** [comment] 2021-08-17 08:09
@Quorum75  Devs are working on it. Will be fixed in one of the next builds.

**Comment by Quorum75** [comment] 2021-12-15 13:05
Issue seems to have disappeared on Beta 4.3.0

**Closed** 2021-12-25 10:58 UTC
Labels: Bug, P3: Medium, Resolution: Cannot Reproduce, Status: Resolved, Version: AdGuard v4.3
