### ISSUE TITLE
Downloading appstore apps too slow with PRO enabled

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#413] opened 2017-06-19 17:20 UTC
When PRO is enabled in adguard. download apps is very slow. I first thought it's my internet. Then I opened adguard. I disabled the PRO option. Then I canceled the download. I clicked again on download and it was super fast. 

So there is an issue with the PRO and downloading apps. Please have a look and fix this issue.

**Comment by Stillness-2** [comment] 2017-06-19 18:44
What version ios? What device? What version Adguard Pro? Does the issue repeat with other downloads?

**Comment by jo2dan23** [comment] 2017-06-19 19:05
Try using opendns server its the fastest one

**Comment by ameshkov** [comment] 2017-06-20 08:45
@worldsdream we do really as much information as possible.

**Comment by worldsdream** [comment] 2017-06-20 16:31
Ios 9.3.3
Latest beta build adguard pro
Iphone 6s

Yes it does repeat with other downloads.

**Comment by jo2dan23** [comment] 2017-06-20 16:33
Do you mean 10.3.3?

**Comment by worldsdream** [comment] 2017-06-20 16:34
Nope. Ios 9.3.3 jailbroken.

**Comment by jo2dan23** [comment] 2017-06-20 17:03
Oh. What dns server are you using?

**Comment by worldsdream** [comment] 2017-06-23 22:18
Adguard default

@meshkov is this a dns issue? I think something else.

**Comment by jo2dan23** [comment] 2017-06-23 22:58
Try opendns home

**Comment by Goddess-Bastet** [comment] 2017-06-25 18:21
I've noticed the same, however I don't disable adguard but just cancel the download then click on the download icon again & it's fast.
IPad Pro 9.7. Ver 10.3.2.

**Comment by Danzee1234** [comment] 2017-06-27 13:37
stop

<a href="http://myurl" >m>Daniel Chhristo</a>

**Comment by ameshkov** [comment] 2017-06-28 22:57
@worldsdream frankly, I've no idea yet.

What exact settings in AG do you have?
System-wide ad blocking?
Custom DNS?

As I recall, we handle iOS9 differently (specifically, IPv6 routes).

**Comment by worldsdream** [comment] 2017-07-12 21:04
I did also try: 

System wide adblocking: on
Dns settings: system default

I searched for an app, clicked on download. It was verrryyyy slow. I clicked on stop. I clicked again, it was fast. Just like @goddess-bastet said in previous comment.

**Comment by ameshkov** [comment] 2017-07-13 10:14
So it happens randomly. I guess this is indeed caused by blocking something, but it will be quite hard to find out what exactly.

Assigned to v1.2.3. I hope we'll add an option to enable/disable AG Pro blocking on a per-app basis in that version.

**Comment by ameshkov** [comment] 2017-08-08 14:25
Guys, we finally realized what happens:
http://joemaller.com/2577/itunes-slowdowns-with-google-dns/

**Comment by vozersky** [comment] 2017-12-05 11:29
maybe we could exclude some apple domain names from our dns filtering?

**Comment by ameshkov** [comment] 2017-12-17 18:39
Unfortunately, the only way to solve this (if it occurred) is to not use third-party DNS.

Once we finish #545 people will be able to import a block list and use it locally without using a third-party DNS server.

**Closed by ameshkov** 2017-12-17 18:39 UTC
Labels: Cannot Reproduce
