### ISSUE TITLE
DNS protection drains battery

### ISSUE THREAD

**Issue by iceglen** [AdguardTeam/AdguardForiOS#2167] opened 2023-05-08 08:40 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed - (might be a copy of this issue - https://github.com/AdguardTeam/AdguardForiOS/issues/1899)

### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.4.6 (998)
- **Device model and storage size:**
  - iPhone 13 256 Gb
- **Operating system and version:**
  - 16.4.1 (a)
- **Browser or App:**
  - not applicable

### Expected Behavior

It worked nice before upgrading to iOS 16. Single battery charge lasted for 2-3 days.

### Actual Behavior

After iOS upgrade battery started to disappear within 24 hours. Doesn't matter if battery saver was turned on or off. 20-30% overnight, the rest of the battery would be eaten during the day. Sometimes AdGuard showed background activity in battery statistics, but it didn't show the amount of consumed energy ("-" sign next to application name). Reinstallation (with VPN profile removing) didn't help.

I left my phone with turned on debug logging for 10 hours. Here they are - [AdGuard_logs.zip](https://github.com/AdguardTeam/AdguardForiOS/files/11419402/AdGuard_logs.zip).

**Comment by Versty** [comment] 2023-05-16 10:26
@iceglen Thank you for the details provided. We are examining the logs.

**Comment by Versty** [comment] 2023-07-13 16:30
@iceglen Information from the logs points to the duplicate of the #1899 issue. The fix is in progress and is currently planned for the version 4.6. 

Upgrading to the latest iOS version may also help to lower battery usage by AdGuard application. 
Please give it a try! 


Closed as a duplicate of #1899.

**Closed** 2023-07-13 16:33 UTC
Labels: Duplicate, Priority: P4
