### ISSUE TITLE
When report an issue on the site, two options aren't automatically selected in the App configuration tab

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForiOS#1690] opened 2020-12-20 00:24 UTC
### Issue Details
- **AdGuard version:**
  - AdGuard for iOS v. 4.0.4 
- **Device model and storage size:**
  - iPhone XR 64 GB 
- **Operating system and version:**
  - iOS 14.3 

### Expected Behavior
Option "Do you use System-wide filtering (for AdGuard Pro versions prior to 1.3.0 only)?" and "Do you use a custom DNS server (if you don't use AdGuard Pro, select "No")?" will be automatically filled in correctly.

### Actual Behavior
Option "Do you use System-wide filtering (for AdGuard Pro versions prior to 1.3.0 only)?" and "Do you use a custom DNS server (if you don't use AdGuard Pro, select "No")?" are not automatically filled in.

### Screenshots
<details><summary>Screenshot:</summary>

![IMG_0306](https://user-images.githubusercontent.com/19418601/102702288-4702c180-4272-11eb-97d2-128a2978b66c.PNG)

</details>

### Additional Information
The problem appeared in version 4.0.4. There was no such problem in version 4.0.3 and earlier.

**Comment by slavaleleka** [comment] 2021-01-29 09:11
@Rakleed reporting tool has been updated so it should be fixed now. could you please try again? let us know if the issue is still there

**Closed by slavaleleka** 2021-01-29 09:11 UTC
Labels: Bug, P4: P4: Low

**Comment by Rakleed** [comment] 2021-01-29 17:48
"Do you use DNS filtering?" option selected incorrectly, since I have DNS filtering enabled.

<details>
<summary>Details</summary>

![IMG_0498](https://user-images.githubusercontent.com/19418601/106309504-48f97080-6273-11eb-8cf0-e3c99a434784.PNG)

![IMG_0497](https://user-images.githubusercontent.com/19418601/106309509-49920700-6273-11eb-8c08-8455602a2334.PNG)

</details>

**Comment by slavaleleka** [comment] 2021-02-01 08:33
could you please share the url of the page which is open after you choose "Report the issue" in the app?

**Comment by Rakleed** [comment] 2021-02-01 09:26
https://reports.adguard.com/en/new_issue.html?dns.enabled=false&product_type=iOS&url=https:%2F%2Fgithub.com%2FAdguardTeam%2FAdguardForiOS%2Fissues%2F1690%23issuecomment-770674285&filters=1.2.3.4.11.14&ios.simplified=false&product_version=4.0.4&browser=Safari

**Comment by Rakleed** [comment] 2021-02-21 22:12
@slavaleleka in the new version 4.1.0, the value of the option "Do you use Simplified filters mode for Safari Content Blocker?" is not automatically selected, but for the option "Do you use DNS filtering?"  the value "No" is selected, although I have DNS filtering enabled.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/19418601/108640472-ee86b500-74aa-11eb-89df-73d18034438f.png)

![image](https://user-images.githubusercontent.com/19418601/108640475-f3e3ff80-74aa-11eb-9a52-8b9a3b3f1c5b.png)

</details>
