### ISSUE TITLE
Background update doesn't work.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForiOS#77] opened 2016-03-15 20:46 UTC
User reports he's got to enter the app to manually update the filters every few days.
Please see JJK-306-26395 for logs.

**Comment by vbagirov** [comment] 2016-03-22 12:00
The problem is also present here: YSY-876-10836

**Comment by Stillness-2** [comment] 2016-03-29 11:16
possible it fixed in the feature/issues/35 branch

**Comment by vozersky** [comment] 2016-03-29 11:37
Also reported here XVI-720-70819

**Comment by Stillness-2** [comment] 2016-04-08 08:58
new

**Closed** 2016-04-08 08:58 UTC
Labels: Bug
