### ISSUE TITLE
VPN restarts when going from different app to adguard log section 4.1.1 (668)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1765] opened 2021-05-26 18:45 UTC
i hope this can be fixed before the next official release. basically my adguard app was left open on the dns log part and when i switched to adguard in the task switcher it restarts the vpn. this bug started a while back. it wasn't during updating the filters either.

https://ufile.io/4ca69h7t

restart between 13:38-13:41

**Comment by Aydinv13** [comment] 2021-05-27 17:00
@jordanelliott23 We are releasing new version soon so please check this behaviour on it.  Thank you!

**Comment by Aydinv13** [comment] 2021-06-10 14:19
@jordanelliott23 please check it on our new release version 4.2.0

**Comment by jordanelliott23** [comment] 2021-06-14 19:05
i cannot tell if it's because its trying to update or what but it happened again but after checking the dns log it reached out to the filter update url. so idk. i wish we could set the auto update thing to intervals. or make it so it only auto checks for filter updates every 24 hours. i guess that would be alot of work to implement?

**Comment by Aydinv13** [comment] 2021-07-01 09:12
@jordanelliott23  I'm sorry for the late response, could you reproduce the problem using debug logs (Settings-> General-> Advanced Settings-> Debug logs)? Then send them to apple@adguard.com
I guess it's not caused by the log section however we have to find out what exactly triggers to update

**Comment by zzebrum** [comment] 2021-07-08 15:22
@jordanelliott23 btw filter update will be completely reworked in the next version

**Comment by anastenko** [comment] 2021-07-22 08:29
I'm closing this issue due to no reply. Please re-open it if the issue still persists after the new version update.

**Closed** 2021-07-22 08:30 UTC
Labels: P3: Medium, Question
