### ISSUE TITLE
Filters have an incorrect update date

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardForiOS#1851] opened 2021-12-07 22:02 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.3.0
- **Device model and storage size:**
  - iPhone 13 Pro 128gb
- **Operating system and version:**
  - 15.1.1

### Expected Behavior

Filters should update and the updated date should be correct in the app. 

### Actual Behavior

I updated the filters and it showed a message that the filters were updated but the "last updated date" is still 3rd December (same date when the 4.3.0 version was released via TestFlight). 
Checking the filter shows it's latest version is from 7th December. 
Not sure if it just shows wrong in the app or if the filter isn't updated correctly. 
I created the support ticket 560140 with the logs (not sure if they are helpful). 

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/10995998/145112814-46d3086e-17c2-4bf5-9d58-0799743e6f5c.png)

![image](https://user-images.githubusercontent.com/10995998/145112823-1de25a7e-443f-4e90-93c5-e600b6e7a76a.png)

</details>

**Comment by danidoedel** [comment] 2021-12-07 22:09
The version number shows correctly so I guess it's just the date not updating correctly.

**Comment by AleksandrShulgin** [comment] 2021-12-08 08:29
@danidoedel Hi
Thanks so much for your issue!
Yes, it's a known problem and we're working on solving this.
In this case, the date is simply displayed incorrectly, but the update is successful.

**Comment by bradenglund** [comment] 2021-12-13 15:46
> In this case, the date is simply displayed incorrectly, but the update is successful.

I am experiencing the same issue on v4.3. I can confirm the same as above that the version number is updated but not the timestamp of the update.

**Comment by planet0** [comment] 2021-12-24 21:58
Looks like this has been fixed as of 4.3.0(915)

**Closed** 2021-12-27 08:01 UTC
Labels: Bug, P3: Medium, Resolution: Fixed, Status: Resolved, Version: AdGuard v4.3, Version: AdGuard v4.3 beta 2, Middle
