### ISSUE TITLE
Counters in Filter section are null

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForiOS#944] opened 2019-04-04 12:49 UTC
Counters in Filter section are null after clean install or update from the previous version.

**Comment by IvanIin** [comment] 2019-05-06 15:47
fixed in 122

**Comment by aspasskaya** [comment] 2019-05-17 11:18
doesn't fixed in 126

**Comment by ameshkov** [comment] 2019-05-23 11:35
Cannot reproduce this on .134

**Closed** 2019-06-25 13:26 UTC
Labels: Bug, P4: Low, UI
