### ISSUE TITLE
SFErrorDomain error=3

### ISSUE THREAD

**Issue by nursery01** [AdguardTeam/AdguardForiOS#2223] opened 2023-09-21 02:18 UTC
IOS 17.0

4GB RAM

AdGuard for IOS 4.5.0(1002)

![IMG_0691](https://github.com/AdguardTeam/AdguardForiOS/assets/40170504/bad6e4b1-215d-4896-9ac1-085ae1f7a78d)

I find this site,but i don't know if this is the reason

[https://developer.apple.com/forums/thread/691389](https://developer.apple.com/forums/thread/691389)

**Comment by maxikuzmin** [comment] 2023-09-25 09:36
@nursery01 thank you! We are aware of this problem. We are already in the process of fixing the update issue. This should be fixed in the upcoming 4.6 update
Unfortunately, some users get this error, one of the temporary solutions you can try is to disable Dandelion Sprout's Annoyances. This has worked for some users
Duplicate of #2188

**Closed by maxikuzmin** 2023-09-25 09:36 UTC
Labels: Priority: P4

**Comment by nursery01** [comment] 2023-11-09 14:41
It has performed normally in 4.5.1
