### ISSUE TITLE
About section add Adguard Logo centered in top

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#110] opened 2016-06-29 10:29 UTC
I think that we should have the adguard logo in top centered over there. Represent adguard! Just like whatsapp, tweetbot have it.

What do you think?

**Comment by worldsdream** [comment] 2016-06-29 11:10
This is what I am talking about:

https://www.dropbox.com/s/z5x4y8bw5gbcp3b/IMG_1389%20copy.png?dl=0

**Comment by worldsdream** [comment] 2016-06-29 11:11
@Stillness-2 @ameshkov what do you both think?

**Comment by ameshkov** [comment] 2016-06-29 11:26
This type of logo will look better:
https://adguard.com/images/logo@2x.png

However, I am not an expert. Let @Stillness-2 decide.

**Comment by worldsdream** [comment] 2016-06-29 12:22
As you see, it is showing "<Adguard" text left above, to get back to Adguard main section. If you add the logo with the text Adguard. It's too much Adguard for the eye. It's better in my opinion to have the logo only. 

In the other hand, if you had a main section for example "<Info" in top left corner instead of "<Adguard" to get back to, then I would have recommend the Logo and Adguard text with it.

**Comment by worldsdream** [comment] 2017-06-23 22:35
@Stillness-2 i still love to see an adguard logo in top in the about section. Can this be added please?

**Comment by ameshkov** [comment] 2017-06-28 15:20
@worldsdream sure, the issue is assigned to a milestone.

**Comment by ameshkov** [comment] 2017-12-11 14:44
Was reworked in the new UI

**Closed by ameshkov** 2017-12-11 14:44 UTC
Labels: Enhancement, Wontfix
