### ISSUE TITLE
Select protocol DNS server doesn't work

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#929] opened 2019-03-25 16:41 UTC
### Steps to reproduce
1. Settings -> DNS privacy -> Server -> AdGuard DNS -> Select protocol 'DNSCrypt'

### Expected behavior
The protocol should be changed.

### Actual behavior
The protocol doesn't changed.

**Comment by zzebrum** [comment] 2019-03-26 11:28
duplicate of #916

**Closed by zzebrum** 2019-03-26 11:28 UTC
Labels: Bug, P2: High
