### ISSUE TITLE
Hosts file subscriptions disappear

### ISSUE THREAD

**Issue by stonevil** [AdguardTeam/AdguardForiOS#699] opened 2018-03-09 16:21 UTC
### Steps to reproduce

1. Add Hosts file subscriptions. URL's:
1.1. http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext&useip=0.0.0.0
1.2. https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts
1.3. https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_optional
1.4. Screenshot ![img_0342](https://user-images.githubusercontent.com/129196/37217259-c336e908-23c5-11e8-9a2b-36b53e29d2ae.PNG)
2. Check back subscriptions in 12-24h
3. Subscriptions disappear
4. Screenshot ![img_0330](https://user-images.githubusercontent.com/129196/37217260-c3560b3a-23c5-11e8-822e-e2e42f220ae0.PNG)

### Expected behavior

Subscriptions should stay.

### Actual behavior

Subscriptions disappear.

<details><summary>Screenshot:</summary>
![img_0330](https://user-images.githubusercontent.com/129196/37217260-c3560b3a-23c5-11e8-822e-e2e42f220ae0.PNG)

</details>

### Your environment

* iPhone 6s 64gb
* iOS 11.2.6
* Safari. Not important for this issues
* WiFi AND mobile internet connection

**Comment by ameshkov** [comment] 2018-03-10 01:31
Duplicate of https://github.com/AdguardTeam/AdguardForiOS/issues/575

**Comment by ameshkov** [comment] 2018-03-10 01:31
Btw, the issue is resolved in the v2.0.2, it is already available on the appstore

**Closed by ameshkov** 2018-03-10 01:31 UTC
