### ISSUE TITLE
Adguard PRO reported to slow down loading times of App Store and Music

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForiOS#182] opened 2016-10-13 20:25 UTC
Source:
https://twitter.com/WarmTurtleTank/status/785913367013781508

Requested logs from customer **1429042**

**Comment by BlazDT** [comment] 2018-02-05 17:58
Possible related issue:

https://forum.adguard.com/index.php?threads/apps-laden-im-appstore-nur-ganz-langsam.28026/

**Comment by ameshkov** [comment] 2018-02-19 21:26
Duplicate of #413

Read this for details:
http://joemaller.com/2577/itunes-slowdowns-with-google-dns/

**Closed by ameshkov** 2018-02-19 21:26 UTC
Labels: Duplicate
