### ISSUE TITLE
App crashes when selecting all available "Annoyances" filters

### ISSUE THREAD

**Issue by johnnynomad** [AdguardTeam/AdguardForiOS#1947] opened 2022-02-21 20:50 UTC
### Expected Behavior

I should be able to activate all available filter lists if I want to.

### Actual Behavior

When activating all 7 filter lists under "Annoyances", the app crashes after a couple of seconds. When trying to refresh the filters after a restart it crashes again.
I think the issue is caused by the iOS content filter limit of 50,000. When I manually activated each of the Annoyances lists after another and waited until the changes where fully applied it worked. The app only crashed when I enabled a list that crossed the threshold of 50,000 Annoyances rules in total.

Attached crash analytics:
[Adguard-2022-02-21-214206.ips.zip](https://github.com/AdguardTeam/AdguardForiOS/files/8111978/Adguard-2022-02-21-214206.ips.zip)

**Comment by ameshkov** [comment] 2022-02-28 07:51
@johnnynomad the crash should go away if you update filters.

Generally, this is a duplicate of #1941

**Closed** 2022-02-28 07:51 UTC
Labels: Bug, Resolution: Duplicate, Status: Resolved, Version: AdGuard v4.3.3
