### ISSUE TITLE
AdGuard is blocking Parcel in-app browser

### ISSUE THREAD

**Issue by alvaroto87** [AdguardTeam/AdguardForiOS#1433] opened 2020-01-19 23:18 UTC
Hello,

When you are tracking a parcel using Parcel app and want to "track on website" (I don't know the exact action name as I use the app in Spanish), AdGuard blocks it and the in-app browser shows a message saying the content has been blocked (see image attached).

After enabling and disabling AdGuard's filters, it seems to be the Privacy one which blocks this.

This doesn't happen on Mac.

I've got the latest iOS 13 on an iPhone 7 Plus.

Thanks.

![20200119_231254788_iOS](https://user-images.githubusercontent.com/60078738/72690163-c8f5e200-3b19-11ea-9ac3-02333fce64cb.png)

**Comment by SoLenny** [comment] 2020-01-20 10:52
@alvaroto87 Hello.
I can't reproduce it on my side.  Most likely the problem is in one of the filters you use. Try to selectively turn them off and see if the problem recurs. You can also try adding a site to the whitelist. Click on the share icon -> AdGuard -> turn off filtering on this site.

**Comment by alvaroto87** [comment] 2020-01-20 22:30
Hello,

Turning the filter off (the Privacy one) only works if I do it from Safari Settings (Settings -> Safari -> Content blockers.

If I disable it within AdGuard app, it doesn't work and continues blocking it.

**Comment by krmkrx** [comment] 2022-10-17 22:00
Is there a solution to this? I am experiencing the exact same.

**Comment by Versty** [comment] 2022-10-21 07:21
@

**Comment by jellizaveta** [comment] 2022-10-21 11:38
@krmkrx Hello!
Could you please specify which filters you have enabled?

**Comment by krmkrx** [comment] 2022-10-21 11:41
@jellizaveta All enabled for ad blocking, privacy, social widgets, annoyances, security. Language specific: AdGuard German filter and EasyList Germany enabled.

**Comment by jellizaveta** [comment] 2022-10-21 12:15
@krmkrx Unfortunately, I have not been able to reproduce this issue with your settings. 
Please disable filter lists one by one, if you find which one causes that issue:
1. Please re-enable this filter 
2. Enable advanced mode in settings (Settings tab -> General -> Advanced mode)
3. Open filterling log (Activity tab)
4. Reproduce issue
5. Make a screenshot of filtering log with all blocked requests and upload it here.

**Comment by jellizaveta** [comment] 2022-10-21 16:24
I was able to reproduce it.
Fixed, filters update should be available in 1-2 hours.
Closed via https://github.com/AdguardTeam/AdguardFilters/commit/9a43c6623a97d965063466565c54b976ababd056

**Comment by krmkrx** [comment] 2022-11-23 08:46
Hi, I'd like to reopen this as the same issue in the exact same constellation reappeared.

**Comment by Versty** [comment] 2022-12-05 08:45
@krmkrx Please check for the filters update. 
This issue should be fixed.

**Closed** 2022-12-05 09:08 UTC
Labels: Bug, Resolution: Fixed, Status: Closed
