### ISSUE TITLE
Rework "Contact support" function

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForiOS#387] opened 2017-04-24 20:11 UTC
We send bug reports with standard iOS "Mail" app.

Some people don't use it, so they get an error "No Configured Email" when they try to send a ticket.

This is not a common problem for iOS users at the moment, but we might need to think about reworking it. 

Based on #379

**Comment by zebrum** [comment] 2017-08-22 13:42
duplicate of #70 i guess

**Closed** 2017-08-23 09:55 UTC
Labels: Enhancement
