### ISSUE TITLE
AG update filters not instantly updating?

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#1245] opened 2019-09-14 17:32 UTC
When I am on my ipad 2018 and I hit the filter update button. It does check for updates and it shows for example: 5 filters updates. When I click it again. It shows the same: 5 filters updated. When I wait 10 sec. and do it again, it again shows: 5 filters updated. 

Maybe after 1 min. When i hit the filter update button. It shows. No filters for updating. 

How can this be solved?

What it should do: you hit update. It refreshes and shows the filters are updated. When you hit the button again it should show that all is updated. 

Thank you. 

Ipad 2018
Ios 12.4
Latest AG ios app

**Comment by ameshkov** [comment] 2019-09-14 17:34
Duplicate of https://github.com/AdguardTeam/AdguardForiOS/issues/1041

**Closed by ameshkov** 2019-09-14 17:34 UTC
Labels: Duplicate

**Comment by worldsdream** [comment] 2019-09-14 17:39
Thanks @ameshkov
