### ISSUE TITLE
Pull down to refresh filters

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1623] opened 2020-08-18 13:12 UTC
Please add an option on the start page to pull down to refresh filters, like it's possible in most apps to reload content. It's a simple and user friendly gesture and it will resolve the issue that the "refresh" button in the top right corner is a) not reachable or b) not clickable.

**Comment by danidoedel** [comment] 2020-08-19 19:56
@Maxim-Butov Why are you closing the original issue #645 and not the duplicate one?

**Comment by vozersky** [comment] 2020-08-19 20:04
Duplicate of https://github.com/AdguardTeam/AdguardForiOS/issues/645

**Closed by vozersky** 2020-08-19 20:04 UTC
Labels: Duplicate
