### ISSUE TITLE
No internet when using cellular connection (DNS64 network)

### ISSUE THREAD

**Issue by Goddess-Bastet** [AdguardTeam/AdguardForiOS#1901] opened 2022-01-09 18:45 UTC
Latest AdGuard version: 4.3.1 (919)
IOS: 15.2
Safari browser.

When on a cellular connection (3 network in UK) I have no internet. I have reset the app & even uninstalled & reinstalled it but problem remains. 
If I disable DNS filtering I have internet access.
On WiFi all is fine.

**Comment by SocksPls** [comment] 2022-01-11 04:00
Just checking in to say same problem, same carrier, iOS 14.3

**Comment by lilws** [comment] 2022-01-17 03:01
I got the same problems. But it happens when on Wi-Fi and fall to cellular after lost Wi-Fi connection. If I turn OFF then On AdGuard again, everything work just fine.

So the issue is Wi-Fi with AdGuard ON (internet OK), then change to cellular with AdGuard ON (internet failed), then Restart AdGuard OFF/ON with cellular (internet ok)

I've already emailed AdGuard teams long times ago but since didn't received any answer yet.

Deep in Advanced settings there is an option to "Restart protection when network changes". It should apply to cellular too, problems solve. Please fix this or at least an option for cellular too.

**Comment by zzebrum** [comment] 2022-01-17 10:53
most likely it's a duplicate of #1892. Please check [this.](https://github.com/AdguardTeam/AdguardForiOS/issues/1892#issuecomment-1013256258)

**Comment by ameshkov** [comment] 2022-01-27 13:36
Not a duplicate. The issue is caused by missing DNS64 support in the latest version. Will be fixed soon.

**Closed** 2022-01-27 17:43 UTC
Labels: Bug, P2: High, Resolution: Fixed, Status: Resolved, Version: AdGuard v4.4
