### ISSUE TITLE
DPI bypass feature

### ISSUE THREAD

**Issue by Corsten56** [AdguardTeam/AdguardForiOS#2368] opened 2024-08-20 20:54 UTC
### Issue Details

For now we don't have work solution for iOS as SpoofDPI, goodbyeDPI. byeDPI etc for other platforms (Windows, Linux, MacOS).

### Proposed solution

Need working bypass DPI solution but not VPN. Something like combination of encrypted DNS queries and modification of packets.

### Alternative solution

iOS apps:
1) "Unicorn HTTPS" not working and not updated.
2) "HTTPS Guard: Bypass SNI" also not working.
"Intra for Android" is not ported to iOS.

**Comment by Versty** [comment] 2024-08-22 15:29
@Corsten56 Thank you for suggestion! 
We will consider the implementation of DPI protection. 

Closed as a duplicate of #2076

**Closed as completed** 2024-08-22 15:30 UTC
Labels: Feature request, Resolution: Duplicate, Status: Closed, Priority: P4
