### ISSUE TITLE
'User Filter' fails to block elements

### ISSUE THREAD

**Issue by SebKranz** [AdguardTeam/AdguardForiOS#541] opened 2017-12-09 19:49 UTC
I am unable to block any elements with the User-Filter.

`reddit.com###container > div.App > div.AppMainPage:first-child > div.NavFrame > div.DualPartInterstitial.xpromoMinimal:first-child > div.DualPartInterstitial__content > div.DualPartInterstitial__common
`

this snippet, created by the adguard 'block element on this page'-feature doesn't seem to block anything.

I also tried:

`reddit.com###div.DualPartInterstitialFooter `
`reddit.com###div.App`
`reddit.com###div`           // this should just block every div, right?

Am I missing something here?

**Comment by Alex-302** [comment] 2017-12-11 10:04
hi
please make screenshot. I don't understand, what you trying to block.

**Comment by SebKranz** [comment] 2017-12-11 10:19
![722c54af-5efd-409c-9574-1ce5f1b6c4b9](https://user-images.githubusercontent.com/33868262/33826392-1f67fde4-de65-11e7-8dc7-bbbd6db937bb.jpeg)

**Comment by ameshkov** [comment] 2017-12-17 17:56
Duplicate of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/886

This is some super weird thing specific to reddit.

In order to work the rules should be in lower case:
```
reddit.com##.transparentoverlay__overlay
reddit.com##.dualpartinterstitialfooter
```

**Closed by ameshkov** 2017-12-17 17:56 UTC
Labels: Question
