### ISSUE TITLE
Slow connection when DNS VPN is enabled

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1004] opened 2019-05-22 08:59 UTC
I realized that my connection speed immediately drops while being connected with your DNS Server. I‘m having problems with YouTube videos f.e. Also when I launch Spotify it says „no connection“ for a few seconds.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment] 2019-05-22 13:10
@iDjay does it depend on server type? (doh, dot, DNSCrypt)
Is everything working ok with Cloudflare or Google DNS?

we probably need some log file: reproduce the problem and send it to our support team (settings - Send feedback - Contact support) - in your email mention the link to this issue so we could find it faster.

**Comment by iDjay** [comment] 2019-05-22 13:47
Hey, not sure I used „AdGuard DNS“ and Split Tunnel. Disabled it now and everything works fine. Will try again later.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment] 2019-05-22 16:35
It seems like the connection gets lost after a few minutes, I can‘t access the internet then. Doesn‘t matter which tunnel I‘m using.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment] 2019-05-23 13:40
Seems to work fine with https, so I guess the „TLS“ option causes problems?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MercuryXIII** [comment] 2019-05-23 19:11
I also have this issue.

**Comment by ameshkov** [comment] 2019-05-24 13:02
Yes, it will be better in the next update.

Closing as duplicate of #990

**Closed by ameshkov** 2019-05-24 13:02 UTC
Labels: Waiting for repro

**Comment by MercuryXIII** [comment] 2019-05-24 17:59
Update is now in TestFlight

**Comment by iDjay** [comment] 2019-05-24 18:02
Yes, will Check if it‘s working now :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment] 2019-05-29 18:52
>It seems like the connection gets lost after a few minutes, I can‘t access the internet then. Doesn‘t matter which tunnel I‘m using. ...

@ameshkov issue happening again with 137 build from today

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameshkov** [comment] 2019-05-29 19:13
@iDjay hi, we'll need logs, here's how to send them: https://github.com/AdguardTeam/AdguardForiOS/issues/1021#issuecomment-496029564

**Comment by iDjay** [comment] 2019-06-02 20:19
>@iDjay hi, we'll need logs, here's how to send them: https://github.com/AdguardTeam/AdguardForiOS/issues/1021#issuecomment-496029564

@ameshkov done, happened again while being on YouTube with AdGuard DNS over TLS

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment] 2019-06-04 08:56
@iDjay got your logs, thank you.
