### ISSUE TITLE
Feature: show warning that you need to enable in safari

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#443] opened 2017-07-16 19:29 UTC
Hi,

A friend of mine installed adguard and told me why he is still seeing ads. I told him did you enable filters correctly? He said: yes. I told him. Reinstall again. Reboot phone. But on the end, he did not enable it in phone settings>safari>content blocker>adguard enabled. 

Now what I am saying is: is it possible that if you open adguard and you have not enabled the adguard adblocker in safari settings panel, it shows a warning in the top or any color yellow or red?

**Comment by ameshkov** [comment] 2017-07-17 10:43
Yeah, we want to do it. 

The problem is that detection is asynchronous and may take some time. So we might need to request notifications permission in order to show such a warning.

**Comment by ameshkov** [comment] 2017-10-17 13:55
Duplicate of #437 (almost done btw)

**Closed by ameshkov** 2017-10-17 13:55 UTC
Labels: Enhancement

**Comment by worldsdream** [comment] 2017-10-17 15:41
Great. Thanks for telling.
