### ISSUE TITLE
VPN tunnel does not restart on a network change

### ISSUE THREAD

**Issue by tungsk** [AdguardTeam/AdguardForiOS#1892] opened 2021-12-31 15:43 UTC
Even set the value for reboot VPN when network changes to true. On the version 4.3.1 , when Network change from wifi network to 4g/5g mobile network. 
All app network is disconnected until manual turn off and turn off DNS protection on ADGuard pro app .

**Comment by ammnt** [comment] 2022-01-07 14:05
I also confirm this problem. In the latest version, when you disconnect a Wi-Fi network, domain resolving does not work fine or/and stable until manually re-enable it☹️

**Comment by royerlraph79** [comment] 2022-01-11 05:23
I have this problem too. This update fucked everything up.

**Comment by AleksandrShulgin** [comment] 2022-01-13 09:27
@tungsk 
Please reproduce the problem and send the logs to our email: devteam@adguard.com
Also specify the time when the bug occurred.

**Comment by ammnt** [comment] 2022-01-14 07:39
@AleksandrShulgin, I have sent the logs for you 40 min. ago. Please take a look! Thank you.

**Comment by ameshkov** [comment] 2022-01-14 16:08
Hi everyone, could you please supply some additional info:

1. What country are you from?
2. What's your cellular provider?
3. In case you're aware of that please tell us whether your cellular network is IPv6-only or not.

Also, make sure that "Restart when network changes" setting is disabled (it does not work properly when enabled, this is a confirmed bug we'll fix soon).

**Comment by ammnt** [comment] 2022-01-14 16:38
> Hi everyone, could you please supply some additional info:
> 
> 1. What iOS device do you use?
> 2. iOS version
> 3. What country are you from?
> 4. What's your cellular provider?
> 5. In case you're aware of that please tell us whether your cellular network is IPv6-only or not.
> 
> Also, make sure that "Restart when network changes" setting is disabled (it does not work properly when enabled, this is a confirmed bug we'll fix soon).

1. iPhone XR;
2. iOS 15.2.1;
3. Russia;
4. YOTA;
5. IPv4-only network + AdGuard VPN with the russian location.

Thank you.

**Comment by tungsk** [comment] 2022-01-15 00:06
> Hi everyone, could you please supply some additional info:
> 
> 1. What iOS device do you use?
> 2. iOS version
> 3. What country are you from?
> 4. What's your cellular provider?
> 5. In case you're aware of that please tell us whether your cellular network is IPv6-only or not.
> 
> Also, make sure that "Restart when network changes" setting is disabled (it does not work properly when enabled, this is a confirmed bug we'll fix soon).

1. iPhone 13 Pro Max
2. iOS15.2
3. Hong Kong
4. CSL
5. IPv4 only

**Comment by robcalon** [comment] 2022-01-16 10:55
> Hi everyone, could you please supply some additional info:
> 
> 1. What iOS device do you use?
> 2. iOS version
> 3. What country are you from?
> 4. What's your cellular provider?
> 5. In case you're aware of that please tell us whether your cellular network is IPv6-only or not.
> 
> Also, make sure that "Restart when network changes" setting is disabled (it does not work properly when enabled, this is a confirmed bug we'll fix soon).

1. iPhone 13 Pro
2. iOS 15.2
3. Netherlands
4. KPN
5. IPv4 and IPv6

**Comment by royerlraph79** [comment] 2022-01-17 01:18
1. iPhone 12
2. iOS 14.7.1
3. Canada
4. Fido
5. IPv6 only

**Comment by royerlraph79** [comment] 2022-01-17 01:28
> * iPhone 12
> * iOS 14.7.1
> * Canada
> * Fido
> * Not sure, DNS upstream is always IPv6, but IPv6 tests online claim that my ISP doesn’t support it



> Hi everyone, could you please supply some additional info:
> 
> 1. What iOS device do you use?
> 2. iOS version
> 3. What country are you from?
> 4. What's your cellular provider?
> 5. In case you're aware of that please tell us whether your cellular network is IPv6-only or not.
> 
> Also, make sure that "Restart when network changes" setting is disabled (it does not work properly when enabled, this is a confirmed bug we'll fix soon).

**Comment by royerlraph79** [comment] 2022-01-17 01:29
> Hi everyone, could you please supply some additional info:
> 
> 1. What iOS device do you use?
> 2. iOS version
> 3. What country are you from?
> 4. What's your cellular provider?
> 5. In case you're aware of that please tell us whether your cellular network is IPv6-only or not.
> 
> Also, make sure that "Restart when network changes" setting is disabled (it does not work properly when enabled, this is a confirmed bug we'll fix soon).

1. iPhone 12
2. iOS 14.7.1
3. Canada
4. Fido
5. Not sure, DNS upstream is always IPv6, but IPv6 tests online claim that my ISP doesn’t support it

**Comment by ameshkov** [comment] 2022-01-17 07:14
The new beta version will be available today or tomorrow (depending on the review times).

This new beta will change the following:

1. Fix "Restart when network changes" setting
2. Add more logging to the place where we handle a network change

It should help us understand what went wrong.

Sorry for the troubles, the problem here is that we cannot reproduce this issue on our side so we're in the dark on what could be causing it.

**Comment by royerlraph79** [comment] 2022-01-17 09:51
> The new beta version will be available today or tomorrow (depending on the review times).
> 
> This new beta will change the following:
> 
> 1. Fix "Restart when network changes" setting
> 2. Add more logging to the place where we handle a network change
> 
> It should help us understand what went wrong.
> 
> Sorry for the troubles, the problem here is that we cannot reproduce this issue on our side so we're in the dark on what could be causing it.

The beta is only available for normal AdGuard, but I paid for AdGuard Pro. Is there a beta for AdGuard pro or do I have to pay again??

**Comment by ameshkov** [comment] 2022-01-17 09:56
Possible for AG Pro as well. Please email your Apple ID to `devteam@adguard.com` so that we could add you to the beta testers list. Mention this GH issue in the email.

**Comment by royerlraph79** [comment] 2022-01-17 09:59
Alright, I just did
  
  
  
  
  
  
  

  
  
>

**Comment by zzebrum** [comment] 2022-01-17 10:50
@royerlraph79 I've sent you an invitation to access beta testing via the Testflight app.

**Comment by Goddess-Bastet** [comment] 2022-01-17 12:29
What iOS device do you use?
iOS version
What country are you from?
What's your cellular provider?
In case you're aware of that please tell us whether your cellular network is IPv6-only or not.

IPhone X
IOS 15.2.1
U.K.
3 Network
Don’t know.

Running AdGuard Pro.

**Comment by royerlraph79** [comment] 2022-01-17 19:53
1. iPhone 12
  
2. 14.7.1
  
3. Canada
  
4. Fido
  
5. Not sure, it seems to support IPv4, but the upstream DNS are always IPv6, even when the option to block IPv6 queries is enabled.   
  
  
  
  
  
  
  

  
  
>

**Comment by royerlraph79** [comment] 2022-01-19 02:50
> @royerlraph79 I've sent you an invitation to access beta testing via the Testflight app.

Thanks for the invitation, I downloaded, but nothing changed, it’s just as laggy as ever. Protection still doesn’t restart either.

**Comment by ameshkov** [comment] 2022-01-19 08:15
@royerlraph79 the new beta version (v4.3.2) is currently on review in App Store. Hopefully, it'll be done soon.

The beta app review is conducted once for every new major version. The following beta versions of v4.3.2 will be rolled out automatically, but the first one takes up to 3 days to be reviewed.

**Comment by ameshkov** [comment] 2022-01-20 15:26
The beta version is finally available. Please let us know if it helps or not.

If it's not, please do the following:
1. Settings - Support - Export logs
2. Send the logs to devteam@adguard.com

**Comment by curiosityseeker** [comment] 2022-01-22 16:34
I installed the beta yesterday, and so far the problems in 4.3.1 are gone. The app is fast again, doesn't crash anymore and switching from Wifi to mobile and vice versa works as it should (so far). 

Note, that I have "Restart when network changes" disabled.

**Comment by ameshkov** [comment] 2022-01-22 16:44
Great news! Anyways, if anything even merely suspicious happens again with this version, please let us know and export&send us the logs.

**Comment by royerlraph79** [comment] 2022-01-23 05:12
> Great news! Anyways, if anything even merely suspicious happens again with this version, please let us know and export&send us the logs.

Thank you so much, it’s back to normal 😄

**Comment by curiosityseeker** [comment] 2022-01-28 16:10
> Great news! Anyways, if anything even merely suspicious happens again with this version, please let us know and export&send us the logs.

The beta has worked for me reliably so far. I think I just once had the problem that I had no internet when switching from mobile to wifi (or vice versa). I enabled  "Restart when network changes"  and since then that hasn't happened again.

I'd like to add just one aspect that might be interesting for you. When that problem occurred in 4.3.1, disabling and re-enabling the VPN in the system settings or in AG itself mostly soled the issue - but not always. However, one trick **always** fixed the problem for me: by selecting another DNS server in AG or by switching from, e.g., AdGuard DNS-over-QUIC to dnscrypt (or whatever). So this _might_ be a code path which is worth a closer inspection to find the root of the problem (unless you haven't already done so).

**Comment by royerlraph79** [comment] 2022-01-29 21:53
Now AdGuard won’t auto-update filters

**Comment by ameshkov** [comment] 2022-01-30 12:57
> Now AdGuard won’t auto-update filters

Are you sure? The auto-update process consists of several stages and it depends on iOS how often it lets AG run in the background and go through them. It may easily take several days.

**Comment by royerlraph79** [comment] 2022-01-31 00:44
> Are you sure? The auto-update process consists of several stages and it depends on iOS how often it lets AG run in the background and go through them. It may easily take several days.

Well, normally I would open the app and the VPN would restart indicating my DNS hosts files have been updated, but now I have to do it manually. Also, background app refresh is turned off because I don’t want it.

**Comment by ameshkov** [comment] 2022-02-01 09:14
@royerlraph79 without the background refresh auto-update simply cannot work, this is the only available option to run something in background:).

**Closed** 2022-02-08 10:39 UTC
Labels: Bug, P2: High, Resolution: Fixed, Status: Resolved, Version: AdGuard v4.4
