### ISSUE TITLE
Adguard pro drain battery on ios v14.2

### ISSUE THREAD

**Issue by ReamsX** [AdguardTeam/AdguardForiOS#1683] opened 2020-12-13 02:07 UTC
I aware that when I charge my iphone 12 mini to 100% and unplug it. After night, my battery down from 100% to 90% and make me scare. When I see at battery report, Adguard pro using approximately 10% and I continutely see at vpn time connect, it’s connecting with 6 hours @@ (though night). I re-install it and today I test again, after night.
It’s connecting 38-40 minuters since I wake up.

i think it’s bug and hope fix soon!

**Comment by zzebrum** [comment] 2020-12-15 15:53
@ReamsX which DNS filters do you use? Also, can you provide a screenshot of battery activity?

**Comment by michaelb-ae** [comment] 2020-12-21 00:24
does you use the dns filtering ? (doh, dot or doq ?) because me it was the cause on my iphone Xs max & IOS 14.3, so i have switched to the profile of my adguard home to use the native dot capability of Ios to mitigate the issue.

**Comment by Chinaski1** [comment] 2020-12-28 14:05
I am closing this task because the user is not responding.
Reopen it if the issue still persists.

**Closed** 2020-12-28 14:06 UTC
Labels: iOS
