### ISSUE TITLE
$generichide filters not parsed on iOS [Bug]

### ISSUE THREAD

**Issue by gotitbro** [AdguardTeam/AdguardForiOS#255] opened 2016-11-22 16:03 UTC
The **_Adguard Content Blocker_** for **_iOS_** does not parse filters with `$generichide`  modifier on **_Safari iOS_** but it parses `$elemhide` filters.

### How to reproduce?
Enable "**_Mobile ads filter_**" in **_Adguard_** (it contains `@@||m.beautypageants.in^$generichide`) and go to http://m.beautypageants.in/ and click on any article, you will get an adb warning which the `$generichide` was supposed to fix.

Now add this filter: `@@||m.beautypageants.in^$elemhide` to user filters and visit any article on the website again, you will not get an anti adb warning (this means `$elemhide` was successfully parsed but `$generichide` was not).

This can be tested for other sites as well. Please fix this major issue.

_**Note:** Using **Mobile Safari 10.0** on **iOS 10.1.1** with **Adguard 1.1.1**_

**Comment by Alex-302** [comment] 2016-11-23 12:30
Confirmed on also Android.
Temporary added to Mobile filter
```
@@||m.beautypageants.in^$elemhide
```
Manually renamed element was hidden by generiс element hiding rule
http://ipic.su/img/img7/fs/kiss_568kb.1479904042.png
Our filters doesn't contains specific rules for this domain.
@ameshkov

**Comment by ameshkov** [comment] 2016-11-23 15:28
@Alex-302 can you reproduce it in v2.8?

**Comment by Alex-302** [comment] 2016-11-23 15:41
@ameshkov no. Seems to be works as expected.
On iOS I can read articles only with $elemhide exclusion.

**Comment by ameshkov** [comment] 2016-11-23 15:49
Got it, thank you!

Filed a bug report to extension repo (as iOS version shares rules converter with it):
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/437

@Stillness-2 please update converter when this bug is fixed on extension side.

**Comment by gotitbro** [comment] 2016-12-12 11:50
@ameshkov @Stillness-2 I see that this issue has been resolved with the **Safari extension**, any update on when this might be fixed for the **iOS app**, can't access a lot of websites due to this issue.

**Comment by ameshkov** [comment] 2016-12-12 21:24
iOS beta with the new converter version should be ready by the end of this week.

**Comment by gotitbro** [comment] 2016-12-12 23:48
That's great! Hope this will be pushed to stable branch as well soon.

**Comment by gotitbro** [comment] 2017-01-09 02:49
@ameshkov The recent update for **Adguard for iOS (1.1.4)** does not fix this issue and also breaks the temporary fix with **_$elemhide_**. 
I am unable to access sites like: 
```
http://m.food.ndtv.com/lists/10-quick-party-snacks-720647
http://khabar.ndtv.com/news/world/explosion-rocks-syrias-aleppo-as-residents-return-1641457
```
More info: https://forum.adguard.com/index.php?threads/ndtv-com-anti-adb-ios.18066/#post-120384

I am left completely helpless as I can't even use the $elemhide modifier now to fix this issue, please help.

**Comment by ameshkov** [comment] 2017-01-09 14:24
@gotitbro weird, thanks for reporting it.

**Comment by gotitbro** [comment] 2017-01-18 19:17
@ameshkov Thanks for getting back to me here https://github.com/AdguardTeam/AdguardBrowserExtension/issues/507, I just browsed through some issues and a lot of them seem to be related to this bug, lets push the update for iOS soon as well :)

**Comment by gotitbro** [comment] 2017-01-24 17:31
@ameshkov Any update on when this might be fixed? Can't access an increasing number of websites due to this bug.

**Comment by ameshkov** [comment] 2017-01-24 17:34
@gotitbro it was pushed to beta yesterday

**Comment by gotitbro** [comment] 2017-01-24 20:28
@ameshkov That's good to know, can you tell me how to join the beta?

**Comment by Stillness-2** [comment] 2017-01-25 11:53
#316

**Closed by Stillness-2** 2017-01-25 11:53 UTC
Labels: Bug, Duplicate

**Comment by ameshkov** [comment] 2017-01-25 17:54
@gotitbro yep, here you are:
https://blog.adguard.com/en/adguard-beta-test/

**Comment by gotitbro** [comment] 2017-01-26 17:03
@ameshkov Thanks for the link, I have some questions about TestFlight:
If I am using a beta version of an app through **_TestFlight_** and an update is published on the **_App Store_** will I be able to update to the stable version (if yes do the updates come through **App Store** or **TestFlight**) or I will stay on the current beta version until the beta is pushed?

**Comment by vbagirov** [comment] 2017-01-26 17:16
@gotitbro as far as I know, no, you will not be able to. Only test builds appear in TestFlight, and if there are none, you won't be able to use Adguard (unless you have a purchased Pro version or a free version from AppStore).

**Comment by gotitbro** [comment] 2017-01-26 17:47
@vbagirov The test/beta builds are the one that are ultimately published to the App Store, right? 
And is the external testers limit still 2000?

**Comment by vbagirov** [comment] 2017-01-27 09:23
@gotitbro that's true; the external testers limit is 2,000 but we still have plenty of room, so don't be worried about that. By test builds I mean those builds that we add to TestFlight. Not necessarily each one of them will be released to AppStore, sometimes we roll out multiple beta builds before finally updating the release version.
