### ISSUE TITLE
Filter update issue/UI bug

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardForiOS#1041] opened 2019-05-30 13:40 UTC
After disabling a few filters and then updating the filters AdGuard says it updated 8 filters even though I only have 7 enabled. 

Also clicking to update the filter multiple times always says it updated X filters... but that‘s not possible as there are no new updates each second. 

<details><summary>Screenshot:</summary>

![5AFE9456-8F99-47F9-870C-FAE3412C5B1A](https://user-images.githubusercontent.com/10995998/58636549-e22ef180-82f0-11e9-88cc-741510010d15.jpeg)

![FAA46D90-3273-4129-940E-42AE3A5A566B](https://user-images.githubusercontent.com/10995998/58636550-e22ef180-82f0-11e9-9826-044661776459.jpeg)

</details>

### Your environment

* AdGuard 3.0.0(137)
* Operating system and version: 12.3.1
* Wi-fi

**Comment by planet0** [comment] 2019-06-06 09:22
Also adding that sometimes manually updating sometimes shows 'Updated x Filters' multiple times after several times in a row.

It updated 6 filters, then I tap to update again a few moments later, and it shows that it updated 6 filters again. Then again, and again and again.

If I wait long enough, it will say 'No updates found' eventually.

**Comment by 08kovalchuk03** [comment] 2019-07-02 12:32
When updating the filters, app also updates on-filters which are situated in disabled groups, so it is not a bug
![Simulator Screen Shot - iPhone Xs Max - 2019-07-02 at 15 29 34](https://user-images.githubusercontent.com/52201516/60512890-7e785980-9cde-11e9-92df-5b65a24528bc.png)

**Comment by planet0** [comment] 2019-07-02 12:42
@08kovalchuk03 how about the 'Updated x Filters' bug?

**Comment by 08kovalchuk03** [comment] 2019-07-02 12:46
> @08kovalchuk03 how about the 'Updated x Filters' repetitive update bug?
Still working on it, I saw this bug myself, but I can't catch it now

**Comment by planet0** [comment] 2019-07-02 12:49
> Still working on it, I saw this bug myself, but I can't catch it now

I'll see if I can reproduce it again in 3.0.1(143) soon and let you know if it is still happening on my device.

**Comment by planet0** [comment] 2019-07-02 23:35
@08kovalchuk03 Tested it out, still occuring. The UI has trouble showing the updating if the user taps to update multiple times (spinning wheel on top in iOS shows the update, but AdGuard app shows date of update).

Otherwise, I can tap to update after the 'Updated x filters' message and it still updates immediately.

Would there be any benefit showing the 'Loading filters to Safari' message like the AdGuard Pro or what v2 used to do? Perhaps that is the cause of this occurring with v3, the app doesn't have the chance to process changes like v2 used to prevent the user from doing?

**Comment by zzebrum** [comment] 2019-07-03 15:26
@08kovalchuk03  not fixed in build .151

**Comment by worldsdream** [comment] 2019-09-14 17:39
Yes can confirm. Hopefully we will see a fix.

**Comment by worldsdream** [comment] 2019-09-19 18:15
Fixed with last update on ios.

**Closed** 2019-09-23 13:37 UTC
Labels: Bug, P3: Medium
