### ISSUE TITLE
Beta 3.0 - Video Tutorial Needs Updating

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1020] opened 2019-05-25 00:22 UTC
The video tutorial needs updating. The video indicates that the user needs to enable the AdGuard Pro in Safari settings. Since version 3 contains multiple blockers per category, this needs to be reflected as well in the video.

**Comment by planet0** [comment] 2019-05-25 11:33
Duplicate of #870?

**Comment by ameshkov** [comment] 2019-05-26 20:31
Yep, closed as a duplicate

**Closed by ameshkov** 2019-05-26 20:31 UTC
Labels: Duplicate
