### ISSUE TITLE
The DNS Privacy feature does not open on iOS 13 beta 1

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#1066] opened 2019-06-15 09:35 UTC
> I can't open the DNS privacy function on iOS 13 beta1. This switch can't be opened, I can't choose DNS server, I can't install VPN description file, it will jump to the settings, then nothing happens, I hope to get your help, very thank you!

### Your environment

* Device model and storage size: 
* Operating system and version: 13.0
* Browser (e.g. Safari)
* Wi-fi or mobile internet connection

**Comment by Yuan573** [comment] 2019-06-15 14:01
When I deleted my VPN profile, I also face the same problem.
You can try to reinstall, and open setting to VPN page before you open DNS tunnel.

**Comment by ameshkov** [comment] 2019-06-17 10:21
@IvanIin we should include the fix for this into the next update.

**Comment by IvanIin** [comment] 2019-06-21 11:22
I cannot reproduce this problem on iOs 13 beta 2. It may have been solved by Apple in the iOs update. @Eugene-Savenko, could you ask the user if this problem is being reproduced now?

**Comment by Marco224** [comment] 2019-06-21 17:17
In my case the problem does not occurs with iOS 13 beta 2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Yuan573** [comment] 2019-06-22 03:32
I remove VPN profile in iOS 13 beta 2 again, This problem already doesn't appear.
Maybe it has been fixed by Apple. 👍

**Closed** 2019-06-24 09:12 UTC
Labels: Bug, P2: High
