### ISSUE TITLE
Apple and Google stores blocked in Russia

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardForiOS#1957] opened 2022-03-04 01:25 UTC
Hi, i have read here in italy that Apple and Google stores are blocked now in Russia. This is a problem for the future of Adguard and for the updates?

Thanks. I love you.

**Comment by ameshkov** [comment] 2022-03-06 08:24
They actually unblocked it a day later. But anyways, this one is not really a problem, not all people from the team are in Russia, and we’re working to relocate more people to Cyprus.

What could be a real problem is if Apple decides to block russian developer accounts. You see, even though we upload new apps (e.g. AdGuard VPN) to the normal AdGuard developer account, we cannot transfer AdGuard and AdGuard Pro from the old russian one due to the fact that we once had iCloud entitlements enabled in both apps. This made the transfer impossible and the only solution is to re-upload the app. And re-uploading effectively means a new app so the customers who purchased the old app won’t have they purchased transferred to the new one. 

I hope this all does not happen, but at this point this is what I fear most.

**Closed** 2022-03-06 08:25 UTC
Labels: Question

**Comment by loca-lhost** [comment] 2022-03-07 05:48
Isn't it time the concept of two similar apps be discontinued. You could create special licenses for adguard pro users who show receipt of purchase and migrate them to adguard premium.

**Comment by ameshkov** [comment] 2022-03-07 10:52
@loca-lhost yeah, that's a good idea.

The problem is the migration itself, there's no simple way to reach out to all the existing customers and explain what happened.

> who show receipt of purchase

The problem here is automation of this process. Probably, the only way would be to ask the customers who purchased via App Store to sign up with AdGuard account in the app so that we could learn that there was a purchase via App Store.

Again, I really hope it won't go that far. And if it does, we have enough time to prepare the transfer.
