### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by MartinIIoT** [AdguardTeam/AdguardForiOS#2133] opened 2023-02-23 04:11 UTC
### Problem Description

No problem.

### Proposed Solution

Create 2x2, 4x2 and 4x4 widgets with informations like a last filters update, total status (no. of filters activated, dns status, ...)

**Comment by jslawler** [comment] 2023-02-23 04:42
Duplicate of #1641.

**Closed** 2023-02-28 10:45 UTC
Labels: Duplicate, Feature request
