### ISSUE TITLE
Get rid of "Some content blockers are disabled message"

### ISSUE THREAD

**Issue by qlee01-dev** [AdguardTeam/AdguardForiOS#2396] opened 2024-11-29 16:02 UTC
### Issue Details

Please add a feature to not show it again

### Proposed solution

N/A

### Alternative solution

N/A

**Comment by dnmTX** [comment] 2024-11-30 00:23
I second that !!!!!!

**Comment by Versty** [comment] 2024-12-03 11:23
@qlee001 Will be improved in future versions. 

Duplicate of #1920

**Closed as completed** 2024-12-03 11:33 UTC
Labels: Feature request, Resolution: Duplicate, Status: Closed, Priority: P4
